### ISSUE TITLE
Handle traitlet messages during cell execution

### ISSUE THREAD

**Issue by dsblank** [ipython/traitlets#105]
We have the need to be able to stay in a loop waiting for a widget value to change while executing cell code. Here is a little version of the desire:

```python
from ipywidgets import widgets
from IPython.display import display
i = widgets.IntText()
display(i)
i.value = 78
while i.value == 78:
    pass
```
We would like to be able to change the value in the displayed IntText and have the loop stop when the detected value changes. I understand that jupyter is not designed to do this, but we would like to replicate a pre-existing API in the notebook.

Is it possible, while the cell is executing, to call a kernel function that will process queued comm messages? This might not be a long term solution, but is necessary for the existing architecture.

**Comment by dsblank** [comment]
This is probably in the wrong place. Probably should be in "notebook", yes?

**Comment by minrk** [comment]
@dsblank sorry about the many-repo confusion. ipykernel or ipywidgets would be the place, depending on whether it's specific to widgets or handling messages in general.

**Comment by dsblank** [comment]
No problem! I spelled the issue out a bit more clearly, and moved to:
https://github.com/ipython/ipykernel/issues/65
