### ISSUE TITLE
Don't use root logger

### ISSUE THREAD

**Issue by ulope** [ipython/traitlets#112]
If no "Application" logger is available `traitlets.log.get_logger()` falls back to grabbing the root logger.

This makes it impossible to selectively silence it's debugging output - for example the (IMO quite useless) ["Using default logger" message](https://github.com/ipython/traitlets/blob/master/traitlets/config/loader.py#L342).

To reproduce:
```python
import IPython
import logging

logging.basicConfig(level=logging.DEBUG)
IPython.embed()
```

**Comment by rkern** [comment]
Fixed by #233.
