### ISSUE TITLE
Always call super in init

### ISSUE THREAD

**Issue by NeilGirdhar** [ipython/traitlets#113]
`HasTraits.__init__` does not call super.  It must call super if you want to use `HasTraits` in multiple inheritance.

`HasTraits` also silently swallows positional arguments.  Why does it do that?

Finally, it would be nice if `HasTraits.__init__` did not automatically set its keyword arguments onto the object.  The problem with this is it means that `HasTraits` must be the final class in the mro, which is hard to guarantee.  Is this behaviour really necessary?

**Comment by NeilGirdhar** [comment]
@rmorshea These are bugs that need to be fixed please by the way.  This is a basic requirement of multiple inheritance in Python.

**Comment by rmorshea** [comment]
1. I think `super().__init__` is left out because `HasTraits` inherits from object.
2. If I'm right this change in #173 is the positional argument problem you mentioned?
3. Value setting from kwargs in `HasTraits.__init__` isn't something I'm attached to, but others probably are, and I imagine it'd represent a pretty big API breakage that would have to come in `v5.0` if it were to come at all.

**Comment by NeilGirdhar** [comment]
1. That doesn't matter.  A class can inherit from `HasTraits` and something else, which is why you must call `super`.  E.g.

```
class B:
   def __init__(self, *, x, **kwargs):
         super().__init__(**kwargs)
         self.y = f(x)

class A(HasTraits, B):
    pass
```

is broken.  `B.__init__` is never called.

2. Yes, thank you!
3. This breaks multiple inheritance.  I personally don't think it's good Python.  The only class that does this is `dict`, and I think that was a mistake that's unfortunately too late to fix.  However, it is not too late for `traitlets`.

**Comment by rmorshea** [comment]
@NeilGirdhar see - #174

**Comment by rmorshea** [comment]
As for the value setting with kwargs, I'd create a separate issue for it and ping minrk, ellisonbg, and SylvainCorlay. I'm not sure what their reasons have been for keeping it so I can't speak for them on that.

**Comment by NeilGirdhar** [comment]
@rmorshea Okay thanks.  Note that unless you forward the `kwargs` to the super call in https://github.com/ipython/traitlets/pull/174, my example above is still broken since `x` will be swallowed before it ever reaches `B.__init__`.

**Comment by rmorshea** [comment]
Unfortunately you can't do that since `object.__init__` doesn't accept any args or kwargs.

**Comment by NeilGirdhar** [comment]
@rmorshea You just forward them.  If none of the superclasses consume them, then you're right that `object.__init__` will raise.  If there are none left, then there is no problem.  This is how cooperative multiple inheritance works in Python.

**Comment by minrk** [comment]
Args are passed through to super in #175
