### ISSUE TITLE
make SingletonConfigurable a subclass of LoggingConfigurable

### ISSUE THREAD

**Issue by Carreau** [ipython/traitlets#118]
Most subclass of SingletonConfigurable are Applications that redefine a `log` trait. 

Exception is InteractiveShell in IPython which define the old way a `self.logger`. And LaTeXTool in IPython that does not use log. 

Once this is done we can do that in load config (roughly):
````python
if name in traits:
   ...
elif isinstance(self, LoggingConfigurable):
       from difflib import get_close_matches
       m = get_close_matches(name, traits)
       if m:
           self.log("{} not in config, do you mean one of: {}".format(name, m))  
```

**Comment by minrk** [comment]
fine with me.
