### ISSUE TITLE
Handling Unknown Arguments

### ISSUE THREAD

**Issue by Lull3rSkat3r** [ipython/traitlets#145]
I was wondering if there is a way for me to configure the command line args parsing to raise an error when an unknown argument is specified. For example, say I have a traitlet class called `Foo` with properties `quo` and `bar`. If I start my and specify an invalid argument such as `--Faux.bar` or `--Foo.qaux` I would like an error to be thrown.

**Comment by minrk** [comment]
There's not a simple flag to turn this on right now, but it should be possible to implement. What's difficult is that the command-line parser doesn't actually know what classes it may configure, so it can't determine whether those are valid or not (it can validate the shortcut aliases and flags, just not Class.trait = value). But the Application does ~know this based on its `classes` attribute, which is a *not-necessarily-authoritative* list of classes it *knows* it will configure. If you are building an application that cannot load any user-defined classes, then it can be treated as an authoritative list and fail on unrecognized traits.
