### ISSUE TITLE
Notification Dict Construction and Routing

### ISSUE THREAD

**Issue by rmorshea** [ipython/traitlets#147]
One of the things I've been thinking about recently is how notification dicts ought to be made, and then routed to their appropriate event handlers. At the moment `_notify_trait` receives several arguments from a `TraitType`, constructs a change dict, and then distributes it to `notify_change`. In the future, it seems like making `_notify_trait` responsible for constructing these notification dicts will make it difficult to generalize this process for events other than changes. It makes more sense to me that `TraitTypes` would be responsible for constructing dicts such that `_notify_trait` would know how to route them.

**Comment by SylvainCorlay** [comment]
@rmorshea `_notify_trait` is meant to disappear to the benefit of direct calls to `notify_change`. The only reason why we have not done it yet is because `ipywidgets` overloads it (i.e. uses the private method). As soon as ipywidgets 5.0 is released, we will remove the `_notify_trait` method.

**Comment by rmorshea** [comment]
The only reason I can see something like `notify_trait` being useful is if there were a generalized way of selecting the appropriate event handlers based on information given in the `dict`. Is that something worth considering for the future, or do you see a series of methods like `notify_<type>` being employed instead.
