### ISSUE TITLE
Many traits have inappropriate defaults for general usage.

### ISSUE THREAD

**Issue by ssanderson** [ipython/traitlets#165]
Several of the built-in traitlets provide default values that I think are inappropriate for general usage.

The general theme is that most traits provide a "falsey" value, but there are many use-cases where a falsey value is not a sane default.  In what sense, for example, is an empty string an appropriate default for **_all**_ `Unicode` instances, or an empty list appropriate as a default for **_all**_ `List` instances?

This issue is exacerbated by the fact that it's quite hard to override the built-in default handling behavior, especially for non-scalar types.  Providing more conservative versions of traitlets requires relying pretty intimately on implementation details of the base traits. My best attempt at doing so is [here](https://github.com/quantopian/serializable-traitlets/blob/master/straitlets/traits.py), with the most relevant bits being [here](https://github.com/quantopian/serializable-traitlets/blob/master/straitlets/traits.py#L19-L21) and [here](https://github.com/quantopian/serializable-traitlets/blob/master/straitlets/traits.py#L56-L111).

The main source of difficulty is that the subclasses of `Container` and `Instance` have inconsistent logic for converting the parameters to their constructors into `*args` and `**kwargs` for their default value factories (some have `default_value=Undefined` in their `__init__` signatures, others have `default_value=None`; `Tuple` just does a `metadata.pop('default_value')`), and none of them provide a sensible path for causing `make_dynamic_default` to raise an error if a user hasn't supplied a specific default.

I realize that removing many of the "default defaults" would represent a pretty serious API breakage (though I'd argue it would be a breakage for the better that would be straightforward for downstream consumers to fix, likely surfacing latent bugs in the process).  A less aggressive change would be providing more conservative versions of the built-in traits, or at least refactoring the existing traits to provide a clear path for making traits that require users to be explicit about their defaults.

**Comment by rmorshea** [comment]
@ssanderson, just to gauge the sort of design changes you're looking for:

+ With respect to overriding the built-in default handling behavior, is a default validation behavior associated with `@default` /  `@validate` preferable to new under the hood heuristics for `TraitType`?
+ Concerning `Container` and `Instance`, I'll look into what's going on in their `__init__` constructor to see if things can be made more uniform. As for the `make_dynamic_default` issue, I think that could be solved if we choose to make changes to `@default` or `@validate` like I mentioned above, but maybe that's not what's best?

**Comment by minrk** [comment]
>  In what sense, for example, is an empty string an appropriate default for all Unicode instances, or an empty list appropriate as a default for all List instances?

I would say: In the sense that it's the only logical default value for all of them. I take your point on more complex things that may or may not be instantiated (e.g. Instance), but for all of the str/list/tuple/dict, I would be very surprised if the default were anything other than the default value for the given type. I disagree that it would be an improvement for it to be otherwise.

But providing a nice API for specifying "A value must explicitly be provided to me, I have no default" is sensible, and seems to solve the actual problem here regardless of the 'default default' issue.

**Comment by SylvainCorlay** [comment]
> Tuple just does a metadata.pop('default_value'))

This one could be considered a bug IMO.

**Comment by minrk** [comment]
The tuple case is a laziness of signature, allowing default_value to be passed positionally or as a kwarg. e.g.

```python
Tuple((1,2,3))
```

and

```python
Tuple(default_value=(1,2,3))
```

are equivalent. It's a bit of a sloppy implementation of what should be

```python
Tuple(default_value=..., **deprecated_metadata)
```

which allows the same positional-or-kwarg specification like any normal Python function.

**Comment by SylvainCorlay** [comment]
Yeah, it is just that the `**metadata` argument name is bad since we decided that passing metadata as keyword arguments was deprecated in favor of `.tag`.

**Comment by SylvainCorlay** [comment]
> I realize that removing many of the "default defaults" would represent a pretty serious API breakage (though I'd argue it would be a breakage for the better that would be straightforward for downstream consumers to fix, likely surfacing latent bugs in the process). 

We did change the API in a backward incompatible way when we decided that `allow_none` should default to `False` for all trait types by default.

However, I would be :-1: for removing the "default defaults", with the exception of `Instance`. In this case, the current behavior is that a trait type with a `foo = Instance(Foo)` attribute will fail to instantiate if the constructor is not passed a keyword argument `foo=some instance of Foo` (which makes sense).
On the other hand, in the case where `allow_none` is `True`, it will succeed by initializing `foo` as `None`. I am not sure it is a good idea and if we should not rather encourage people to specify the `None` default value.

**Comment by ssanderson** [comment]
@rmorshea in my ideal world where the API was being designed from scratch, doing something like:
```
class MyClass(HasTraits):
    x = Integer() # Note that no default_value was set.

MyClass().x
```
would raise an error indicating that no default value was specified for `x`.

My argument for this behavior is that there is no value appropriate for use as a default value for a type that represents an integer field of an arbitrary object.  I agree with @minrk's sentiment that 0 is the only sane choice ***if we have to choose a default***.  I just don't think it's universal enough to be forced on every usage of `Integer` by default.  I'd rather have an API that asks me to clarify my intent than one that tries to guess what I mean without enough information to do so reliably.

In my experience, liberal default values tend to create bugs that manifest far away from their root causes, which at best wastes developer time tracking down where the bad value actually entered the system, and at worst encourages band-aid solutions that try to handle malformed values where they cause issues rather than where they're introduced.  

In the case of traitlets specifically, the failure-at-a-distance problem is made worse by the fact that `HasTraits` accepts arbitrary keyword arguments.  On more than one occasion, I've had the frustrating experience of tracing an unexpected 0 or False value in a trait to having made a typo in a traited object's constructor or config file.

**Comment by rmorshea** [comment]
@ssanderson I see what you're saying. I wasn't sure if you were also unhappy with validation of defaults, since default values don't pass through handlers registered with `@validate`, which IMO seems off (though I understand `@validate` is supposed to be meant for "cross-validation" and not all validation).

**Comment by rmorshea** [comment]
@ssanderson given how much time has passed and the increased need for backwards compatibility in Traitlets I don't think we will be able to change how default values are handled. Closing for now...
