### ISSUE TITLE
DeprecationWarning in traitlets

### ISSUE THREAD

**Issue by hiamandeep** [ipython/traitlets#199]
executing this in Jupyter notebook,     
    
    class MyWidget(widgets.DOMWidget):
        _view_name = Unicode('MyView', sync=True)
        value = Unicode(input_form+javascript, sync=True)

gives warning:   

home/aman/mylatex/lib/python2.7/site-packages/ipykernel/__main__.py:2: DeprecationWarning: metadata {'sync': True} was set from the constructor.  Metadata should be set using the .tag() method, e.g., Int().tag(key1='value1', key2='value2')
  from ipykernel import kernelapp as app
/home/aman/mylatex/lib/python2.7/site-packages/ipykernel/__main__.py:3: DeprecationWarning: metadata {'sync': True} was set from the constructor.  Metadata should be set using the .tag() method, e.g., Int().tag(key1='value1', key2='value2')
  app.launch_new_instance()

Can't figure out how to solve this.

**Comment by SylvainCorlay** [comment]
Instead of passing `sync=True` as a keyword argument, use the tag function.

```python
_view_name = Unicode('MyView').tag (sync=True) 
```

**Comment by hiamandeep** [comment]
Thanks!
