### ISSUE TITLE
Deprecate/remove help_classes, config_classes?

### ISSUE THREAD

**Issue by takluyver** [ipython/traitlets#20]
At some point, we added functionality to describe different lists of classes in the `--help-all` output and the config file. I think this might have been when frontend config could be passed to kernels, but we didn't want to show those options in help output.

We're not using this functionality now, as far as I can see, and it's a little bit of extra confusing indirection to follow. I'd suggest we get rid of it again and just use `classes`.

**Comment by minrk** [comment]
I think you are right - this was only used in ConsoleApp as far as I can tell, where CLI args could affect the kernel, but config files could not. ConsoleApp no longer has this behavior.
