### ISSUE TITLE
alias warnings after switching to nose2

### ISSUE THREAD

**Issue by rmorshea** [ipython/traitlets#202]
After switching to nose2, I'm getting a series of warnings while testing the `KVArgParseConfigLoader`:

```
test_basic (traitlets.config.tests.test_loader.TestArgParseKVCL) ... ['--a=10', '--b=20', '--Foo.Bar.value=10', '--Foo.Bam.value=list(range(10))', "--D.C.value='hi there'"]
WARNING:devnull:Unrecognized alias: '--a=10', it will probably have no effect.
WARNING:devnull:Unrecognized alias: '--b=20', it will probably have no effect.
```

There are others, but they're all of the same form.

**Comment by rmorshea** [comment]
This doesn't seem to have anything to do with Traitlets since these warning are being raised, but not shown when using `nose` (unless it's a problem that warnings are being raised). Is there way to configure `nose2` so that I won't get these warnings?

**Comment by minrk** [comment]
I think those are expected, so we can either add expect-logs, or tweak the tests.
