### ISSUE TITLE
ironpython - absolute_import

### ISSUE THREAD

**Issue by swn1** [ipython/traitlets#212]
The import from __future__ in config/configurable.py needs to add , absolute_import

It's causing an error when loading from jupyter_client under IronPython (2.7.5).  I think this may be the only change needed in this lib, somebody want to add it for me and save me making a one-word pull request?

**Comment by minrk** [comment]
@swn1 can you tell us what module is being imported incorrectly, and what exactly the error is? It's a bit odd that IronPython would behave differently from CPython 2.7 in this regard.

**Comment by swn1** [comment]
Without the absolute_import clause I get this:
`
C:\Program Files (x86)\IronPython 2.7>ipy64 -X:Frames
IronPython 2.7.5 (2.7.5.0) on .NET 4.0.30319.42000 (64-bit)
Type "help", "copyright", "credits" or "license" for more information.
>>> import sys
>>> sys.path.insert(0, r"c:\users\steve\jupyter_client")
>>> sys.path.insert(0, r"c:\users\steve\jupyter_core")
>>> sys.path.insert(0, r"c:\users\steve\ironzmq")
>>>
>>> import jupyter_client as jc
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "c:\users\steve\jupyter_client\jupyter_client\__init__.py", line 4, in <m
odule>
  File "c:\users\steve\jupyter_client\jupyter_client\connect.py", line 23, in <m
odule>
  File "C:\Program Files (x86)\IronPython 2.7\lib\site-packages\traitlets\config
\__init__.py", line 6, in <module>
  File "C:\Program Files (x86)\IronPython 2.7\lib\site-packages\traitlets\config
\application.py", line 18, in <module>
  File "C:\Program Files (x86)\IronPython 2.7\lib\site-packages\traitlets\config
\configurable.py", line 13, in <module>
ImportError: No module named traitlets

>>>`

My copy of jupyter_client is, so far, unmodified.  ironmzq is a stiched-together mess, mostly copied from pymzq but with the whole backend structure ripped out and replaced by clrmzq4.  I tried dropping the .NET zeromq bindings in under backend but it got very messy so I'm trying it this way, may go back.

The traitlets code I'm running is pip-installed, 4.2.1.

The call site in jupyter_client looks like this:
`from __future__ import absolute_import

import glob
import json
import os
import socket
import tempfile
import warnings
from getpass import getpass

import zmq

from traitlets.config import LoggingConfigurable
from .localinterfaces import localhost
from ipython_genutils.path import filefind`

And works with the suggested change.

**Comment by minrk** [comment]
I won't oppose the change in #213, but that seems like a bug in ironpython, because there is no `traitlets.py` in `traitlets/config`. That means absolute_import should have no effect in `traitlets/config/configurable.py` according to Python's defined behavior.

**Comment by swn1** [comment]
I reached a similar conclusion, that there is something askew in the implementation of import, based on some other breadcrumbs I've found along the way.  Behavior seems to depend on history in ways it shouldn't.  In IronPython import also searches the loaded .NET namespaces so it's definitely different.  But I'm just a beginner in this codebase, Thanks for the expert review.
