### ISSUE TITLE
observe's handler change should likely be an object.

### ISSUE THREAD

**Issue by Carreau** [ipython/traitlets#217]
It always have the same field, and is annoying to access through keys.
Maybe a NameTuple for immutability ? not sure if you can access a named tuple with square brackets.

**Comment by minrk** [comment]
Generally this is called a Bunch. We have a few implementations scattered about as `ipstruct`, etc., but there [isn't an implementation in the stdlib](http://bugs.python.org/issue1094542).

**Comment by Carreau** [comment]
> but there isn't an implementation in the stdlib.

is that [true](https://docs.python.org/3/library/types.html#types.SimpleNamespace) ?

```
class types.SimpleNamespace
A simple object subclass that provides attribute access to its namespace, as well as a meaningful repr.

Unlike object, with SimpleNamespace you can add and remove attributes. If a SimpleNamespace object is initialized with keyword arguments, those are directly added to the underlying namespace.

The type is roughly equivalent to the following code:

class SimpleNamespace:
    def __init__(self, **kwargs):
        self.__dict__.update(kwargs)

    def __repr__(self):
        keys = sorted(self.__dict__)
        items = ("{}={!r}".format(k, self.__dict__[k]) for k in keys)
        return "{}({})".format(type(self).__name__, ", ".join(items))

    def __eq__(self, other):
        return self.__dict__ == other.__dict__
SimpleNamespace may be useful as a replacement for class NS: pass. However, for a structured record type use namedtuple() instead.

New in version 3.3.
```

**Comment by rmorshea** [comment]
@Carreau, that has the attr access, however we'd still need dict-like syntax for compatibility.

**Comment by Carreau** [comment]
Yes, I was aware that __getitem__ was missing, the usual implementation of
Bunch, like the one linked In Min's comment does not have it though.

Wondering if `class Bunch(SimpleNamespace, dict):pass` would work as
expected. On my phone though so will try later.
On May 30, 2016 18:15, "Ryan Morshead" <notifications@github.com> wrote:

@Carreau <https://github.com/Carreau>, that has the attr access, however
we'd still need dict-like syntax for compatibility.

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/ipython/traitlets/issues/217#issuecomment-222572694>,
or mute the thread
<https://github.com/notifications/unsubscribe/AAUez8IIZIik21c-c7QSinPp2_d6ViQBks5qG4vFgaJpZM4IfyfR>
.

**Comment by rmorshea** [comment]
@Carreau, I just realized that with `class Bunch(SimpleNamespace, dict): pass` you have to keep two different sources up to date, `Bunch().__dict__` and the dict that is `Bunch()`. In other words, when you do `b.attr = 1` this won't be reflect in `b['attr']` and you'll get a key error because only `b.__dict__` got updated.
