### ISSUE TITLE
don't use `assert`.

### ISSUE THREAD

**Issue by Carreau** [ipython/traitlets#219]
Assert is meant optimised out by `-O` Python, which means that it is not equivalent to raise. 
Should be replaced by actual exceptions raising. 

Was introduced in #200, slipped through review.

**Comment by SylvainCorlay** [comment]
Agreed

**Comment by minrk** [comment]
When I look through traitlets, I see asserts only used for argument-type verification. Isn't this exactly what asserts are for, and what `-O` is meant to optimize-out?
