### ISSUE TITLE
4.3 Api breakage. 

### ISSUE THREAD

**Issue by Carreau** [ipython/traitlets#231]
#209 changed `HasTraits.traits` from an instance method to a class method. You can't do that it breaks stuff.

**Comment by Carreau** [comment]
@rmorshea @ellisonbg

**Comment by rmorshea** [comment]
What kind of breakage has this caused? Instance still use the method in the same way they always have.

**Comment by Carreau** [comment]
```
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.5.0/lib/python3.5/site-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/home/travis/build/ipython/ipython/IPython/core/tests/test_magic.py", line 90, in test_config
    _ip.magic('config')
  File "/home/travis/build/ipython/ipython/IPython/core/interactiveshell.py", line 2158, in magic
    return self.run_line_magic(magic_name, magic_arg_s)
  File "/home/travis/build/ipython/ipython/IPython/core/interactiveshell.py", line 2079, in run_line_magic
    result = fn(*args,**kwargs)
  File "<decorator-gen-47>", line 2, in config
  File "/home/travis/build/ipython/ipython/IPython/core/magic.py", line 188, in <lambda>
    call = lambda f, *a, **k: f(*a, **k)
  File "/home/travis/build/ipython/ipython/IPython/core/magics/config.py", line 114, in config
    configurables = [ c for c in self.shell.configurables
  File "/home/travis/build/ipython/ipython/IPython/core/magics/config.py", line 115, in <listcomp>
    if c.__class__.traits(config=True) ]
TypeError: traits() missing 1 required positional argument: 'self'
```

**Comment by Carreau** [comment]
You can't do that. You can't even change the name of a positional argument, as the **can** be used as kwarg.

**Comment by Carreau** [comment]
```
In [1]: def foo(a,b):
   ...:     return a-b
   ...:
   ...:

In [2]: foo(b=1,a=2)
Out[2]: 1

In [3]: def foo(a,c):
   ...:     return a-c

In [4]: foo(b=1,a=2)
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-4-20ec935d796b> in <module>()
----> 1 foo(b=1,a=2)

TypeError: foo() got an unexpected keyword argument 'b'
```

**Comment by Carreau** [comment]
`has_trait` also changed signature.

**Comment by Carreau** [comment]
> What kind of breakage has this caused? Instances still use the method in the same way they always have.

No because you can call the methods on the class themselves, in this case it change.

**Comment by Carreau** [comment]
`trait_names` also changed.

**Comment by ellisonbg** [comment]
Is this a change we have released yet or just something we would release in 4.3? @SylvainCorlay thoughts?

**Comment by Carreau** [comment]
No it's not released.

**Comment by SylvainCorlay** [comment]
This is not released.

**Comment by rmorshea** [comment]
Yes, `traits`, `trait_names`, and `has_trait` were changed to `classmethods`, but this was primarily done because under the hood having these and `class_<method>` was redundant. The difference in api when accessing these methods from the class shouldn't actually be any different because `class_traits` is already a classmethod.

I'm confused by the traceback, but I'm guessing it's an issue with how it was overridden in config?

**Comment by Carreau** [comment]
Note that IPython 5.x will be LTS, so we will have a traitlet LTS. I would like to know which version of traitlet to use, or if I some point we should just split traitlets in "traitlets for widgets" that move at the same pace, and "Traitlets for Configurable applications" that stop changing.

**Comment by Carreau** [comment]
> Yes, traits, trait_names, and has_trait were changed to classmethods, but this was primarily done because under the hood having these and class_<method> was redundant. The difference in api when accessing these methods from the class shouldn't actually be any different because class_traits is already a classmethod.
> 
> I'm confused by the traceback, but I'm guessing it's an issue with how it was overridden in config?

Technically I can use `__class__.traits(config=True)`  and pinned traitlets to 4.3+ (which I do not want to do), but the problem is I have 2 methods, on the same objects, quasi-similar signature on 2 differents minor revisions, which is highly confusing.

Agree i'm starting to age,  and I might be becoming and old beardy geek that complain how it was better before, but there is already a huge shift of API between 4.0 and 4.1, 4.2 have some changes too, and 4.3 start to have quite a few more, and I don't want to track 4 API in my head, as well as 4 API on users machines. 

So for the  time being, I'm fine making **provisional API**, that is to say, API that are shipped, but which are **explicitly marked as "might change without notice** and don't ask user to use it. 
That's what Python does in many places. 

But with the current rhythm of change, you will start to annoy even people that are happy to dig through the changes and go through the pain of understanding the issues.

**Comment by rmorshea** [comment]
@Carreau gotcha, good to know. I can't remember where I commented on the redundancy, but in passing, I think @SylvainCorlay had mentioned this was something he might be for.

As far as versioning and things of that sort, maybe we should try to soften the rate of change?

**Comment by ellisonbg** [comment]
I don't know the details of these AIPs right now.

The first thing to establish is whether or not a public API has changed that might be released in 4.3. @rmorshea are you saying that no APIs have changed, just implementation and that the problem @Carreau is running into is something else?

@Carreau can you provide a self contained bit of code that worked in 4.2 not won't work in master?

@Carreau we have been very careful thus far in the 4.x series to not break APIs. Do you know of other breakages?

It should be fine to introduce new APIs in point releases and the ones we have added have been very carefully designed and are *not* in my mind provisional.

**Comment by rmorshea** [comment]
@ellisonbg `traits`, `trait_names` and `has_traits` have been converted to classmethods. So at a surface level, these methods appear to be unchanged, but `has_traits_instance.__class__.<method>` would reveal otherwise. At an instance level though, these methods operate identically.

Additionally deprecation warnings have been added to the `class_<method>` methods (these operated exactly the same as `traits`, `trait_names`, and `has_trait` but were classmethods).

The specific traceback @Carreau would be resolve with `c.traits(config=True)` since `c` is a configurable.

**Comment by Carreau** [comment]
> @Carreau can you provide a self contained bit of code that worked in 4.2 not won't work in master?

I'll try to come up with a simple non-contrived example. 

> @Carreau we have been very careful thus far in the 4.x series to not break APIs. Do you know of other breakages?

No, but I haven't played with traitlets a lots, and I think the number of people using it is too low to assume that it get enough review for various use case. See
 - #215 
 - #217 
 - #218 
 - #219 
 - #222 

Which are symptoms of the same people seeing the same code over and over again which make you blind to your own way of coding (I'm definitively guilty of this one as well, and I know it can be really hard to get out of it). And I'm obviously biased, as I opened all of the above cited issues, but I literally opened all of these in 1h by just upgrading IPython to use new Traitlets **4.1** API, and right now you are about to release 4.3. So it basically mean that the all time from 4.1 release to now go Zero usage of traitlets new API beyond your use cases. 


> @ellisonbg traits, trait_names and has_traits have been converted to classmethods. So at a surface level, these methods appear to be unchanged, but has_traits_instance.__class__.<method> would reveal otherwise. When accessing them from an instance, these methods operate identically. Effectively, class_<method> has changed to <method>, while leaving the old class_<method> there for posterity with a deprecation warning.

Yes, not that big of a deal as in the case **I** have, I can only use it if I pin to >= 4.3 but in case of inheritance, you suddenly break all the subclass that would overwrite  one of above cited methods.

**Comment by rmorshea** [comment]
@Carreau in terms of inheritance, classmethods work with `super`:

```python
class A(object):
    @classmethod
    def f(cls):
        print(cls)

class B(A):
    def f(self):
        super(B, self).f()
```

**Comment by Carreau** [comment]
Indead, with `super()`, it works, the following does not on master, does on 4.2:

```
from traitlets.config import Configurable
from traitlets import Bool
import traitlets

class OtherMixin():
    pass

class Foo(OtherMixin, Configurable):
    a = Bool()
    b = Bool()
    
    def traits(self, **metadata):
        res = Configurable.traits(self, **metadata)
        res['x'] = 3
        return res
    
Foo().traits(), traitlets.__version__
``` 

`TypeError: traits() takes 1 positional argument but 2 were given`


And just [this friday](https://github.com/ipython/ipython/pull/9489/files) I had to explicitelty explicitely one parent as `super()` was not doing the right thing.

**Comment by Carreau** [comment]
> And just this friday I had to  explicitly one parent as super() was not doing the right thing.

Fair enough it was not with traitlets, and multiple inheritance is rare...

**Comment by rmorshea** [comment]
@Carreau would you be opposed to still phasing `class_traits`, but keeping `traits` an instance method? The main reason I brought of the change in #209 is that having both is redundant, not that `traits` needed to be a classmethod.

**Comment by Carreau** [comment]
> @Carreau would you be opposed to still phasing out class_traits, but keeping traits an instance method

Hum, I would have to check for other use case in IPython, i'm not 100% sure we can do without class methods, especially in the help system. I don't remember if the help system instantiate traits or not.

Right now I just spent a couple of PR upgrading IPython/IPykernel to the new API, which is again changing. So I'm a bit... (stress/worried/concern/`<whatever english term I don't know, can't figure out the right words>`) about what's coming next, and that's without considering that all our packages are not upgraded yet.

**Comment by minrk** [comment]
@rmorshea we definitely need to keep the mechanism for requesting traits on a class.

Currently, I think we should just revert #209. There is little to no benefit in removing redundant code if it changes behavior *at all*, so we can just go ahead and keep `class_foo` methods around forever. I don't see a downside to that.

**Comment by rmorshea** [comment]
@minrk That's fine I think I'm just anal about keeping things clean.

At this point the issues (here and in other people's code) may be too compounded to surmount, but in looking at them again, I'm pretty sure the problem is just that instances methods are being referenced from a class, when it would actually be appropriate to use the classmethod. However, as you point out, this isn't exactly something that will create problems in the future.

I'll have to make a new pr for the `trait_events` methods.

**Comment by minrk** [comment]
@rmorshea I opened #234 to *just* deprecate the classmethod changes, so `trait_events` is left alone.

**Comment by rmorshea** [comment]
@Carreau close the issue?

**Comment by Carreau** [comment]
Haven't tried, but I'll trust you and Min. 

I'll complain again if I have issues, that's how github is supposed to work right ?

**Comment by minrk** [comment]
Thanks for staying on top of things, @Carreau!
