### ISSUE TITLE
Bounded Integer

### ISSUE THREAD

**Issue by pbugnion** [ipython/traitlets#259]
The `Int` traitlet supports bounds, but not the `Integer` traitlet:

```python
import traitlets

class A(traitlets.HasTraits):
    bounded_integer = traitlets.Integer(default_value=traitlets.Undefined, min=5, max=100)

class B(traitlets.HasTraits):
    bounded_int = traitlets.Int(default_value=traitlets.Undefined, min=5, max=100)

a = A(bounded_integer=200) # raises a TraitError, as expected
a = B(bounded_int=200) # does not raise
```

This behaviour is a little confusing, since the docs recommend using the Integer traitlet rather than Int.

Is there any reason this was implemented this way (see PR #33)?

I'm happy to put in a PR for a bounded Integer if this would be useful.

**Comment by minrk** [comment]
Yes, bounds should be checked. This is an oversight on Python 2, because `Integer is Int` in Python 3. If you want to add that PR, that would be fine.

**Comment by pbugnion** [comment]
Thanks! I'll put in a PR.

**Comment by minrk** [comment]
Great, thanks!
