### ISSUE TITLE
Uninformative error for union of two enums

### ISSUE THREAD

**Issue by jakevdp** [ipython/traitlets#260]
When you have a union of two Enums and pass an invalid value, the error message is not particularly informative:

> TraitError: The 'val' trait of a Foo instance must be any value or any value, but a value of 'AB' <class 'str'> was specified.

This came up in the programmatically-generated pieces of the Altair API (see https://github.com/ellisonbg/altair/issues/168), so it's not as easy as simply re-writing the expression as a single Enum.

How difficult would it be to improve this error message?

Example:

```python
import traitlets as T

class Foo(T.HasTraits):
    val = T.Union([T.Enum(['a', 'b', 'c']), T.Enum(['A', 'B', 'C'])])
    
Foo(val='AB')
```
```
<snip>
/Users/jakevdp/anaconda/lib/python3.5/site-packages/traitlets/traitlets.py in error(self, obj, value)
    596             e = "The '%s' trait must be %s, but a value of %r was specified." \
    597                 % (self.name, self.info(), repr_type(value))
--> 598         raise TraitError(e)
    599 
    600     def get_metadata(self, key, default=None):

TraitError: The 'val' trait of a Foo instance must be any value or any value, but a value of 'AB' <class 'str'> was specified.
```

**Comment by SylvainCorlay** [comment]
Yes, the Union uses the `info_text` property of trait types to assemble error messages, but in many case, this property is not set.

For example:
```
print(Enum().info_text)
print(Int().info_text)
```
returns
```
any value
an int
```

**Comment by jakevdp** [comment]
Is it as simple as creating an informative ``info_text`` property for these classes?

**Comment by SylvainCorlay** [comment]
Yes I think so.

Although we should use this occasion to make the validation error messages
for the other custom types all use info_text.
