### ISSUE TITLE
Set c.Application.log_format will be error

### ISSUE THREAD

**Issue by Anne623** [ipython/traitlets#268]
Hi, I remove the comment in `jupyter_notebook_config.py`,

```
c.Application.log_format = '[%(name)s]%(highlevel)s %(message)s'
```

while when i run notebook ,it will be error, the error log is

```
Logged from file notebookapp.py, line 1138
Traceback (most recent call last):
  File "E:\Program Files (x86)\Anaconda\lib\logging\__init__.py", line 859, in emit
    msg = self.format(record)
  File "E:\Program Files (x86)\Anaconda\lib\logging\__init__.py", line 732, in format
    return fmt.format(record)
  File "E:\Program Files (x86)\Anaconda\lib\site-packages\tornado-4.2-py2.7-win-amd64.egg\tornado\log.py", line 164, in format
    formatted = self._fmt % record.__dict__
KeyError: u'highlevel'
Logged from file notebookapp.py, line 1138
```

**Comment by rmorshea** [comment]
I'm not sure this has to do with `traitlets`, but to be sure, what version of the notebook do you have?

**Comment by Anne623** [comment]
@rmorshea , I use notebook 4.2.1, that when I set ```'[%(asctime)s,%(msecs).03d] [%(levelname)s] [%(name)s] %(message)s'```, it works fine.

**Comment by minrk** [comment]
@Anne623 what fields are available depends on what log formatter is used. That string was generated by a default that adds a `highlevel` name, but the notebook application uses a different log formatter, provided by tornado, which has different fields available.
