### ISSUE TITLE
How can a subcommand refer to its parent command?

### ISSUE THREAD

**Issue by ankostis** [ipython/traitlets#286]
What is the right way for a sub-command to refer to the parent command?
I note that sub-commands, unlike a sub-configurable, have not their `parent` property set to point the parent command when initialized.

**Comment by minrk** [comment]
I'm not sure that there is a mechanism for this at the moment. What do you need this for?

**Comment by ankostis** [comment]
I want to create a subcommand that saves the parent's default-configs, like that:

    $ foo gen-config

This is equivanlent to `jupyter --generate-config` option.

I can workaround it by overriding `initialize_subcommands()` at [traitlets/config/application.py#L445](https://github.com/ipython/traitlets/blob/master/traitlets/config/application.py#L445) in my class like this:

```python
class FooApp(Application):
    @catch_config_error
    def initialize_subcommand(self, subc, argv=None):
        ...
        self.subapp = subapp.instance(parent=self)
        ...
````

The config of the parent gets propagated normally to the child subcommand.
So my question is: Is there a reason for not always setting subcommand's `parent` property?

**Comment by minrk** [comment]
>  Is there a reason for not always setting subcommand's parent property?

Don't think so. Just never came up. #292
