### ISSUE TITLE
Enhance `--help-all` to print all relevant  configurables, along with their relations

### ISSUE THREAD

**Issue by ankostis** [ipython/traitlets#296]
Now that an elaborate traversal of **"Configurable-inheritance"**  got merged (#289) for when generating the sample config-file (hopefully everything works all right),
is there a reason why the same logic is not used when printing the `--help-all`  message?
(i.e. to reduce the clutter in the terminal?)

Specifically in [traitlets/config/application.py#L384](https://github.com/ipython/traitlets/blob/master/traitlets/config/application.py#L384) where the classes to examine gets decided, there is this line:

    help_classes = self.classes

I would expect to find:

    help_classes =  = self._classes_inc_parents(self)  

but I've tested with even with the new `self._classes_in_config_sample()` method and it works fine.

A PR for this would be trivial, but now that `parent` is appropriately set on sub-commands (#292),
~~we can~~ *it may be possible to*  traverse the **"commands-chain"**, to provide also hints about them on the help & sample-config-file sections, like that:  

    [root-cmd  previous-sub-cmd]  *sub-cmd(parent1, parent2)

[*] It is the `sub-cmd` that is documented above.

**Comment by minrk** [comment]
Yes, I think `--help-all` should have similar logic to the generated config files.

I don't believe traversing the parent command chain would be appropriate for `--help-all`, though, because different subcommands configure different things. The presence of parent applications should have no bearing on what `--help-all` outputs for a given command.

**Comment by ankostis** [comment]
> The presence of parent applications should have no bearing on what --help-all outputs for a given command.

I agree, the configuration properties mud be the same. 
I'm thinking of just printing the parent-command to orient the user for which cmd the help message is about?

**Comment by minrk** [comment]
I don't think the parent command should be displayed (e.g. `git commit -h` doesn't tell you anything about its parent, `git`).
