### ISSUE TITLE
Did change['old'] cease to exist?

### ISSUE THREAD

**Issue by michaelpacer** [ipython/traitlets#312]
I was trying to work through the examples of `@observe` in order to debug some nbconvert stuff. And all the examples involve printing `change['old']`, but when I try to do this, I run into errors. When I look at the `traitlets.py` file I see places where new gets defined, but I'm having difficulty finding where `old` is. Are the documentation examples simply out of date?

**Comment by SylvainCorlay** [comment]
I am not reproducing the issue. Do you have an example where `old` is not there?

PS: `@validate` callbacks take a dict that don't have a `old` key.

**Comment by SylvainCorlay** [comment]
@michaelpacer should we close this one?

**Comment by rmorshea** [comment]
I think we can close this one.

cc: @michaelpacer

**Comment by michaelpacer** [comment]
I don't remember what this came up in the context of at this point, sorry for not responding before.

But I'll reopen if i run into this again.
