### ISSUE TITLE
Deprecate get_default_value method?

### ISSUE THREAD

**Issue by takluyver** [ipython/traitlets#32]
From PR #31 - the `get_default_value` method on traits now just returns `self.default_value` in all the traits we define. Dynamically created defaults (e.g. for `Instance` traitlets) are built via a different mechanism, so that we can avoid creating them until they're needed.

If there are no other traitlets defining or using `get_default_value`, we can deprecate it and just use `self.default_value` instead. Widgets [doesn't appear to](https://github.com/ipython/ipywidgets/blob/master/ipywidgets/widgets/trait_types.py). Are there any other users of widgets we know about?

CC @minrk @SylvainCorlay

**Comment by SylvainCorlay** [comment]
I am not aware of any code depending on `get_default_value`. :+1: to deprecate it.
