### ISSUE TITLE
Add a callable traitlet type

### ISSUE THREAD

**Issue by yuvipanda** [ipython/traitlets#321]
This would be useful when you need to pass in a function. I've run into this several times when writing JupyterHub spawners. Environment variables can be specified as a dict whose value can be callable in JupyterHub, for example. I'm implementing this in one of my spawners just now, and think it'll be useful in the core library too.

Would people be open to a patch that added a callable traitlet type? if so, should it support further validation? The only one I could think of that'll make sense in Python would be an arity check...

**Comment by yuvipanda** [comment]
I actually instead solved it like https://github.com/jupyterhub/systemdspawner/commit/8d9fbc8030334127ce876e72beaba941c57992c6 instead, which exposed a much smaller customization surface. This helps a lot when maintaining backwards compatibility, so perhaps not having a callable is a good idea! :)

**Comment by minrk** [comment]
I'd be fine adding callable. It's also achievable with Any + validation:

```python
class C(HasTraits):
    f = Any()
    @validate('f')
    def _(self, proposal):
        if not callable(proposal.value):
            raise TraitError("I need a callable!")
        return proposal.value
```

**Comment by travigd** [comment]
Seems that the `Callable` trait isn't available in traitlets via pypi nor is it detailed in the documentation.

**Comment by danielballan** [comment]
I added it to the docs here https://github.com/ipython/traitlets/pull/523
