### ISSUE TITLE
No tests are run

### ISSUE THREAD

**Issue by yurivict** [ipython/traitlets#328]
When run from the FreeBSD port, it never runs any tests:
```
running test
running egg_info
writing requirements to traitlets.egg-info/requires.txt
writing traitlets.egg-info/PKG-INFO
writing top-level names to traitlets.egg-info/top_level.txt
writing dependency_links to traitlets.egg-info/dependency_links.txt
reading manifest file 'traitlets.egg-info/SOURCES.txt'
writing manifest file 'traitlets.egg-info/SOURCES.txt'
running build_ext

----------------------------------------------------------------------
Ran 0 tests in 0.000s
```

Not sure if this is OS-specific, or a generic problem, but tests should run when setup.py suggests there are tests.

**Comment by minrk** [comment]
This is probably something in the port, not the package. We don't claim that `setup.py test` should work. In the current repo:

    $ python setup.py test
    error: invalid command 'test'

To run the tests:

    py.test traitlets

**Comment by yurivict** [comment]
```py.test traitlets``` works. Thanks!
