### ISSUE TITLE
Default value of Union is not respected

### ISSUE THREAD

**Issue by jakevdp** [ipython/traitlets#344]
Ran into this today: it seems the specified default value for ``traitlets.Union`` is not respected.

```python
import traitlets as T

class Foo(T.HasTraits):
    unicode = T.Unicode(allow_none=True, default_value=None)
    unicode_or_list = T.Union([T.Unicode(), T.List(T.Unicode())],
                              allow_none=True, default_value=None)
    
f = Foo()
print(f.unicode)  # This is None as expected
print(f.unicode_or_list)  # This is an empty string, should be None?
```

The workaround is to specify the default value within the first entry of the Union's list, but I found this behavior surprising. Is it a bug?

**Comment by rmorshea** [comment]
This is likely a consequence of #332. I'll look into it.

**Comment by rmorshea** [comment]
A test case class was inheriting from `HasTraits` instead of `TestCase` so it never showed this failure.

`Union` now  triggers `subclass_init` in it's "sub-traittypes" instead of implementing `make_dynamic_default`.
