### ISSUE TITLE
"Edit on Github" link on docs broken for stable

### ISSUE THREAD

**Issue by cdeil** [ipython/traitlets#348]
I noticed that the "edit on Github" link at
http://traitlets.readthedocs.io/en/stable/
points to
https://github.com/ipython/traitlets/blob/186518a091d1ca05af0039cd4f147f1c2a649cd6/docs/source/index.rst
which doesn't exist.

I tried to have a quick look if this is a known issue and found:
https://github.com/rtfd/readthedocs.org/issues/1637
Not sure if it's related.

**Comment by minrk** [comment]
I'm not sure what to do here. RTD is in total control of this, so it seems like it can only be a bug there. I don't know how they got the wrong ref. The `latest` links are correct, at least.

**Comment by rmorshea** [comment]
No longer broken.
