### ISSUE TITLE
Behaviour of HasTraits.observe(<handler>, <trait>, type=All)

### ISSUE THREAD

**Issue by ajwdewit** [ipython/traitlets#351]
I tested the dynamic observe on HasTraits attributes with the following example:

```python
from traitlets import HasTraits, Float, All

class TestTraitlets(HasTraits):
    a = Float()

    def __init__(self):
        HasTraits.__init__(self)
        self.observe(self._a_notified, "a", type=All)

    def _a_notified(self, d):
        print("'{name}' Changed: {old} to {new}".format(**d))

t = TestTraitlets()
print("Initial value of a: ", t.a)
print("Changing a to 2:")
t.a = 2
print("reassigning a to 2:")
t.a = 2
print("Changing a to 3:")
t.a = 3
```
When running it provides the following output:
```
Initial value of a:  0.0
Changing a to 2:
'a' Changed: 0.0 to 2.0
reassigning a to 2:
Changing a to 3:
'a' Changed: 2.0 to 3.0
```

Although the handler gets notified when `a` changes, it is not notified when the same value (2) is reassigned to the trait. Despite that the trait is observed with ```type=All```. Is this the intended behaviour? I would expect that with ```type=All``` all events to a trait are reported to the handler.

**Comment by minrk** [comment]
It's true that change events only fire when the value is actually changed (as opposed to every assignment, regardless of change). `type=All` indicates that all events should be monitored, but currently there is only one type of event - the change event. Soon there will be an element-change event.

**Comment by ajwdewit** [comment]
Thanks for the update.
