### ISSUE TITLE
Move Eventful Traits to IPyWidgets

### ISSUE THREAD

**Issue by rmorshea** [ipython/traitlets#352]
@minrk @SylvainCorlay - I'm not sure how much use eventful traits will see in standard traitlets applications. Would it be more reasonable to move discussions for eventful traits to [ipywidgets](https://github.com/ipython/ipywidgets)?

#327 #278

**Comment by minrk** [comment]
It might! I'd be happy with that.

**Comment by SylvainCorlay** [comment]
I think that it is more general than just widgets. Besides, eventful traits require changes in traitlets core in terms of event compression etc...

**Comment by minrk** [comment]
While it's more general in theory, I'm not sure it is in practice (nowhere in IPython or Jupyter would it be used, for instance). If it's possible, I think it would be beneficial to prototype new things like this in widgets and push them upstream when they are determined to be successful. That's much harder to do when you have to wait for a release of traitlets before widgets can use it, at which point traitlets has committed to an API that can no longer change.

But of course that doesn't work if they can't actually be implemented without changes to traitlets.

**Comment by rmorshea** [comment]
I'd have to double check, but I'm pretty sure #327 is self contained.

**Comment by rmorshea** [comment]
The only thing that's not self contained is rolling back changes. To resolve that, we could implement an api for traits to define their own rollback mechanisms.

**Comment by rmorshea** [comment]
migrated: [ipywidgets/#1071](https://github.com/ipython/ipywidgets/issues/1071)
