### ISSUE TITLE
Change notifications not working for Bytes traitlet

### ISSUE THREAD

**Issue by hannorein** [ipython/traitlets#358]
I've registered to get notifications for changes in a Bytes traitlet via something like

    this.model.on('change:particle_data', this.particle_data_changed, this);

But I never receive any callback. It works for other types of traitlets. Is that expected behaviour or a bug?

**Comment by artur-trzesiok** [comment]
I have exatcly the same problem.

**Comment by rmorshea** [comment]
This is an issue specific to `Bytes` traits?

**Comment by rmorshea** [comment]
Considering that this works with non-bytes traits, and that the `Bytes` implementation is extremely simple, my guess is that this is a downstream problem in widgets.

**Comment by hannorein** [comment]
I agree. I looked at the bytes trait code too and could not figure why this would be different.

**Comment by rmorshea** [comment]
I'm assuming this was fixed downstream. Closing for now...
