### ISSUE TITLE
Traitlets master breaks ipywidgets

### ISSUE THREAD

**Issue by SylvainCorlay** [ipython/traitlets#363]
I have not investigated yet, but we cannot make a release before we figure that one out.

**Comment by ankostis** [comment]
Is there any updates on that?

Launching `jpupyter notebook`  seems to work with latest traitlets, and 
I can see travis passing: 
- https://travis-ci.org/jupyter/jupyter/builds
- https://travis-ci.org/jupyter/notebook/builds
- https://travis-ci.org/jupyter/jupyter_client/builds
- https://travis-ci.org/jupyter/jupyter_core/builds
- https://travis-ci.org/jupyter/jupyter_console/builds

**Comment by SylvainCorlay** [comment]
Not yet, but I will get back to this in the next days.

ipywidgets make the most advanced use of traitlets with a lot of custom validation, roll-backs of changes etc..

**Comment by minrk** [comment]
@ankostis those builds aren't using master of traitlets, the are using the latest release.

**Comment by ankostis** [comment]
Assuming that this serious issue is resolved, would it be possible to have a pre-release of *traitlets* in PyPi?

**Comment by ankostis** [comment]
(I hope you don't get reaaly pissed off by my question)
Is there a reason not to have a pre-release in PyPi, so as to start preparing downstream dependencies?

**Comment by jasongrout** [comment]
I don't see this as a blocker for having a pre-release.

**Comment by SylvainCorlay** [comment]
It seems that this has been solved since I posted the issue. We should be
able to close.

**Comment by ankostis** [comment]
What about a pre-release?

**Comment by rmorshea** [comment]
@SylvainCorlay, are we closing?

**Comment by rmorshea** [comment]
@SylvainCorlay, see https://github.com/ipython/traitlets/pull/413 and https://github.com/jupyter-widgets/ipywidgets/pull/1409

**Comment by vidartf** [comment]
#415 is also necessary for current IPyWidgets master (https://github.com/jupyter-widgets/ipywidgets/commit/88be97136ebeb9d1809bc352550ea4fa967df094), as e.g. the `_module_model` gets resolved incorrectly.

**Comment by takluyver** [comment]
Is this going to be fixed in traitlets, ipywidgets, or both? I'm still seeing test failures on Jenkins because of the incompatibility.

**Comment by takluyver** [comment]
Is there any plan to fix this? It would be nice to get the `traitlets-master-downstream-stable` tests passing again.
