### ISSUE TITLE
Async Trait Observers

### ISSUE THREAD

**Issue by rmorshea** [ipython/traitlets#375]
I'm really just throwing this idea out there to see if there's any demand for it. Perhaps this would be useful for changes that result in a network request? I haven't really thought about it too deeply though.

cc: @rgbkrk @SylvainCorlay @ellisonbg @minrk @tacaswell 

```python
import asyncio
import random


class AsyncTrait(object):
    
    def __set__(self, obj, value):
        task = asyncio.ensure_future(obj.handle(value))
        obj._tasks.append(task)
    
    def __get__(self, obj, cls):
        loop = asyncio.get_event_loop()
        loop.run_until_complete(asyncio.gather(*obj._tasks))
        return obj._x


class HasAsyncTraits(object):
    
    a = AsyncTrait()
    
    def __init__(self):
        self._tasks = []
        self._x = 0
    
    async def handle(self, value):
        await asyncio.sleep(random.random())
        self._x = value

        
obj = HasAsyncTraits()

for i in range(10):
    obj.a = i

# computation occurs now
print(obj.a)
```

**Comment by minrk** [comment]
I think making attribute access or assignment slow enough to warrant async is probably not something I would like to encourage or enable.

**Comment by rmorshea** [comment]
@minrk makes sense. I had imagined that it would be useful for changes that trigger a network request of some sort where you'd end up using async anyway.
