### ISSUE TITLE
Let Dict() accept a Mapping as value (and probably other traitlets their ABC counterparts)

### ISSUE THREAD

**Issue by jankatins** [ipython/traitlets#386]
It seems that currently the traitlet for `Dict` only allows for a real `dict`, but not a Mapping:

https://github.com/ipython/traitlets/blob/master/traitlets/traitlets.py#L2619

```python
     # klass=dict means that each new value will be tested for `isinstance(new_val, dict)
     super(Dict, self).__init__(klass=dict, args=args, **kwargs)
``` 

This means that I can't add a subclass of type `Mapping` to the trait

```python
class MyMap(MutableMapping):
    def __delitem__(self, name):
        pass
    def __getitem__(self, name):
        pass
    def __iter__(self):
        pass
    def __len__(self):
        pass
    def __setitem__(self, name, obj):
        pass
Dict().validate(obj="whatever", value=MyMap())

TraitError: The 'None' trait of a whatever instance must be a dict, but a value of class 'str' (i.e. '') was specified.
```

It would be nice if the traitlets could work with their collections abc counterpart...

I my case I want to pass my own [implementation of a dict](https://github.com/Cadair/jupyter_environment_kernels/blob/master/environment_kernels/lazyobj.py) as [a 'env' into a kernel spec](https://github.com/Cadair/jupyter_environment_kernels/blob/master/environment_kernels/envs_common.py#L53-L62). 

Up to now I put [`dict` as a parent class](https://github.com/Cadair/jupyter_environment_kernels/blob/master/environment_kernels/lazyobj.py#L39) to get around the traitlet check. But this now doesn't work anymore as `dict.update(mapping)` seems to take a few shortcuts if mapping is a subclass of dict. In this case it seems that none of the python functions from the mapping are called and I end up with a unupdated dict. This burns me in https://github.com/jupyter/jupyter_client/blob/master/jupyter_client/manager.py#L252 where the activated environment doesn't get applied (this worked in older python version, but not anymore in the py35 or py36).

**Comment by rmorshea** [comment]
It seems like we should make a `Mapping` `TraitType` or  use `env = Instance(MutableMapping)` instead of changing `Dict`. On the whole `isinstance(new, dict)` is an intuitive and straightforward validation check that does exactly what someone making `Dict` trait would expect.

Doing otherwise would also break #317.
