### ISSUE TITLE
Manually trigger change processing

### ISSUE THREAD

**Issue by jasongrout** [ipython/traitlets#395]
It would be nice if we had a way to manually trigger change processing (validation, notifications) on a certain trait. If a trait holds a mutable container, this would allow us to modify it in-place, and then manually trigger the change process.

This means that we'd have to catch validation errors and do some sensible revert, but it would make it possible to do things more efficiently.

**Comment by rmorshea** [comment]
Would a `catch_trait_notifications` context manager achieve this?

```python
with hastraits.catch_trait_notifications() as changes:
    hastraits.a = value

# do something

for c in changes:
    hastraits.notify_change(c)
```

**Comment by rmorshea** [comment]
I think [spectate](https://python-spectate.readthedocs.io/en/latest) (developed by me) is probably the best way to handle changes that are made to mutable data types.

A feature similar to how spectate allows you to [manually merge notifications](https://python-spectate.readthedocs.io/en/latest) might be useful though.

**Comment by rmorshea** [comment]
I think `spectate` provides a reasonable solution to this problem. I've even added a page of documentation describing [how to use `spectate` with `traitlets`](https://python-spectate.readthedocs.io/en/latest/usage/spectate-in-traitlets.html)
