### ISSUE TITLE
Disallow in traitlets

### ISSUE THREAD

**Issue by djarecka** [ipython/traitlets#397]
Hi,

I'm trying to move a project from traits to traitlets and I can't find anything that looks like [traits_type.Disallow](http://docs.enthought.com/traits/_modules/traits/trait_types.html#Disallow). Can you please confirm that you don't have this kind of objects. 

Basically, I'd like to prevent user from assigning a value to a attribute that was not defined within the class.

Thanks,
Dorota

**Comment by rmorshea** [comment]
Use `TraitType(read_only=True)`.

**Comment by djarecka** [comment]
@rmorshea - thanks for the suggestion. But I believe that traitlets doesn't support the wildcard concept to disallow ALL attributes that are not explicitly defined, am I right?

Just to show the example from traits that would give an error:

```
class MyClass(HasTraits):
    vv = Int() 
    _ = Disallow

mc = MyClass()
mc.k = 3
```

**Comment by rmorshea** [comment]
I see now. No, this is not possible with `traitlets`.

You could achieve the same effect by extending `Hastraits.__setattr__`:

```python

class OnlyTraits(HasTraits):

    def __setattr__(self, name, value):
    	if isinstance(getattr(type(self), name), TraitType):
    	    super(OnlyTraits, self).__setattr__(name, value)
   	else:
   	    raise AttributeError("%s objects have no trait "
   	        "name '%s'" % (type(self).__name__, name))
```

**Comment by djarecka** [comment]
Thanks for your confirmation and suggestion.

Yes, I've started experimenting with overriding the `__setattr__`, and for now I'm using a slightly temporary solution with `if name.startswith("_") or self.__getattribute__(name):`. I'm not completely happy with it, but without including a private attributes I can't initialize an instance. 
I believe `OnlyTraits()` should give you this error:
AttributeError: type object 'OnlyTraits' has no attribute '_trait_values'

**Comment by rmorshea** [comment]
@djarecka there's also magic with `hold_trait_notifications` that will break because we introduce a proxy for `notify_change` in order to catch notifications.

**Comment by rmorshea** [comment]
I'm honestly not sure there's a way to pull this off. It's also quite probable that future releases of `traitlets` will not be compatible with your subclass (however it gets implemented). My suggestion is to trust that users will check whether a trait exists with `HasTraits.has_trait`. Part of why this is difficult to implement is because Python doesn't have public or private namespaces.

**Comment by djarecka** [comment]
I see, will think about it more. 

Answering you previous question: `_ = traits.Disallow` is used in the project mainly to return an error right away if a user makes a typo and wants to initialize a `HasTraits` subclass with an attribute (or set this attribute later) that is not a defined traits in the class.

**Comment by rmorshea** [comment]
@djarecka, it might be reasonable to raise, or at least warn when `**kwargs` in the `HasTraits` constructor are used to set attributes that are not traits. There may be objections to that since it's not backwards compatible, but it could plausibly be merged.

**Comment by rmorshea** [comment]
I think we can close this. The mitigation suggested above is already implemented.
