### ISSUE TITLE
Warn if HasTraits Constructor Causes setting of Non-Traits

### ISSUE THREAD

**Issue by rmorshea** [ipython/traitlets#400]
# Summary

Closes #397, which suggests the inclusion of the `Disallow` wildcard from `traits`. There's no plausible way to fully implement `Disallow` in `traitlets` however, as a compromise, we could warn (or raise) when `HasTraits`' `**kwargs` constructor would set non-traited attributes.

# Background

[`Disallow`](http://docs.enthought.com/traits/traits_user_manual/advanced.html#disallow-object) is a wildcard trait that prevents the getting and setting of attributes on `HasTraits` instance which have not been explicitely defined as Traits on the class. For example:

```python

class MyClass(HasTraits):
    _ = Disallow()

mc = MyClass()
mc.j = 1 # raises
```

**Comment by minrk** [comment]
The constructor already has this warning and doesn't set non-trait attributes:

```python
In [7]: class C(HasTraits):
   ...:     pass
   ...:

In [8]: c = C(a=5)
/Users/benjaminrk/conda/bin/ipython:1: DeprecationWarning: Passing unrecoginized arguments to super(C).__init__(a=5).
object.__init__() takes no parameters
This is deprecated in traitlets 4.2.This error will be raised in a future release of traitlets.

In [9]: c.a
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-9-045efd26f8b5> in <module>()
----> 1 c.a

AttributeError: 'C' object has no attribute 'a'
```

**Comment by rmorshea** [comment]
Yup they are. My bad 😅

**Comment by djarecka** [comment]
I missed this conversation earlier, but I just tried the example suggested by @minrk and I don't have Warnings when running `c = C(a=5)` (I'm using `'5.0.0.dev` version of `traitlets`), but indeed I have  `AttributeError` when asking for `c.a`.

However when I simply try to assign `c.b = 1` there is no error.

**Comment by djarecka** [comment]
@rmorshea @minrk  - just want to come back to my question quickly. Do you have any plans in the nearest future to implement  `Disallow()` concept, so the following code would give an error:
```
class C(HasTraits):
    pass # or something like _ = Disallow()

c = C()
c.b # this should raise  
```

**Comment by minrk** [comment]
There are no plans to disallow normal Python assignment in traitlets.

**Comment by djarecka** [comment]
thank you for confirmation
