### ISSUE TITLE
Traitlets 5.0

### ISSUE THREAD

**Issue by rmorshea** [ipython/traitlets#401]
Thread for discussing the prerequisites for a 5.0 pre-release.

cc: @ankostis @minrk @SylvainCorlay

**Comment by ankostis** [comment]
No pre-requisites.
I believe that we should have a pre-release sooner than later, to keep it as a reference as new behavior gets frantically added, and start summoning more eyeballs.

**Comment by minrk** [comment]
Before making a prerelease, we need to:

- [ ] Go over current PRs for which should actually get into 5.0 (they don't need to all be merged, but we should have a good sense of which are going in and which are to be postponed before telling people "this is approximately what will be new in 5.0")
- [ ] Make sure that all of the changes so far in 5.0 are pretty well documented

**Comment by ankostis** [comment]
Any hope for #99?
My focus if env-vars are ever used is to respect the order described in [this comment](/ipython/traitlets/issues/99#issuecomment-277444643).

**Comment by ankostis** [comment]
Just reminding that env-vars were in the radar - but there is no hurry.
I have vendorized my copy of traitlets for our app, exactly for cases like this.

It is just good to now ahead of time if some solution (ie #439) is good as a starting point, or a dead-end, to plan ahead how much to rely on.

**Comment by minrk** [comment]
@ankostis I think #439 is a great start, just some refinements to do.

**Comment by ankostis** [comment]
A pep8 formatting of the codebase would be great to have t some point before 5.0.0.

**Comment by rmorshea** [comment]
@minrk there's been interest in doing a 4.x release. @Carreau gave my access to the PyPI repo in order to get this done, but I think it'd be best to get some outside input on how to do this given how many things depend on traitlets.

**Comment by minrk** [comment]
The main thing for a 4.x release is what PRs should be backported. There's lots in master that shouldn't be in 4.x. At this point, it should ideally be minimal bugfixes to 4.x, I think. Probably the place to start is open a new Issue for 4.x release to list candidate PRs to backport.

**Comment by Carreau** [comment]
What's the status on Traitlets 5.0 ? this issues is at least 3 years old, and I'm not quite sure what 5.x bring wrt 4.x and how compatible it is. I don't want to break things for the sake of breaking. 

Here is an autogenerated list of the changes I could autodetect: 
<details>

The following items are new:
<pre>
    + traitlets.FuzzyEnum
    + traitlets.config.Container
    + traitlets.config.application.Application.emit_alias_help(self)
    + traitlets.config.application.Application.emit_description(self)
    + traitlets.config.application.Application.emit_examples(self)
    + traitlets.config.application.Application.emit_flag_help(self)
    + traitlets.config.application.Application.emit_help(self, classes=False)
    + traitlets.config.application.Application.emit_help_epilogue(self, classes)
    + traitlets.config.application.Application.emit_options_help(self)
    + traitlets.config.application.Application.emit_subcommands_help(self)
    + traitlets.config.application.Application.start_show_config(self)
    + traitlets.config.application.default_aliases
    + traitlets.config.application.default_flags
    + traitlets.config.application.functools
    + traitlets.config.application.pprint
    + traitlets.config.configurable.Container
    + traitlets.config.configurable.Dict
    + traitlets.config.default_aliases
    + traitlets.config.default_flags
    + traitlets.config.functools
    + traitlets.config.loader.Container
    + traitlets.config.loader.Dict
    + traitlets.config.loader.PY3
    + traitlets.config.loader.Undefined
    + traitlets.config.loader.fnt
    + traitlets.config.loader.string_types
    + traitlets.config.pprint
    + traitlets.traitlets.BaseDescriptor.subclass_init(self, cls)
    + traitlets.traitlets.CaselessStrEnum.info(self)
    + traitlets.traitlets.CaselessStrEnum.info_rst(self)
    + traitlets.traitlets.Enum.info_rst(self)
    + traitlets.traitlets.FuzzyEnum
    + traitlets.traitlets.FuzzyEnum.info(self)
    + traitlets.traitlets.FuzzyEnum.info_rst(self)
    + traitlets.traitlets.FuzzyEnum.validate(self, obj, value)
    + traitlets.traitlets.HasTraits.trait_defaults(self, *names, **metadata)
    + traitlets.traitlets.HasTraits.trait_has_value(self, name)
    + traitlets.traitlets.HasTraits.trait_values(self, **metadata)
    + traitlets.traitlets.TraitType.default(self, obj='None')
    + traitlets.traitlets.Union.default(self, obj='None')
    + traitlets.traitlets.UseEnum.info_rst(self)
    + traitlets.traitlets.__all__
    + traitlets.traitlets.describe
    + traitlets.traitlets.directional_link.link(self)
    + traitlets.traitlets.link.link(self)
    + traitlets.utils.descriptions
    + traitlets.utils.descriptions.__builtins__
    + traitlets.utils.descriptions.__cached__
    + traitlets.utils.descriptions.__doc__
    + traitlets.utils.descriptions.__file__
    + traitlets.utils.descriptions.__loader__
    + traitlets.utils.descriptions.__name__
    + traitlets.utils.descriptions.__package__
    + traitlets.utils.descriptions.__spec__
    + traitlets.utils.descriptions.add_article(name, definite=False, capital=False)
    + traitlets.utils.descriptions.class_of(value)
    + traitlets.utils.descriptions.describe(article, value, name='None', verbose=False, capital=False)
    + traitlets.utils.descriptions.inspect
    + traitlets.utils.descriptions.re
    + traitlets.utils.descriptions.repr_type(obj)
    + traitlets.utils.descriptions.six
    + traitlets.utils.descriptions.types
</pre>

The following items have been removed (or moved to superclass):
<pre>
    - traitlets.ClassTypes
    - traitlets.DefaultHandler
    - traitlets.EventHandler
    - traitlets.ForwardDeclaredMixin
    - traitlets.ObserveHandler
    - traitlets.SequenceTypes
    - traitlets.ValidateHandler
    - traitlets.add_article
    - traitlets.cast_unicode_py2
    - traitlets.class_of
    - traitlets.config.application.decorator
    - traitlets.config.decorator
    - traitlets.config.loader.logging
    - traitlets.contextlib
    - traitlets.enum
    - traitlets.getargspec
    - traitlets.getmembers
    - traitlets.inspect
    - traitlets.is_trait
    - traitlets.isidentifier
    - traitlets.os
    - traitlets.parse_notifier_name
    - traitlets.re
    - traitlets.repr_type
    - traitlets.six
    - traitlets.sys
    - traitlets.traitlets.ClassBasedTraitType.error
    - traitlets.traitlets.Container.element_error
    - traitlets.traitlets.List.validate
    - traitlets.traitlets.TraitType.instance_init
    - traitlets.traitlets.Union.make_dynamic_default
    - traitlets.types
    - traitlets.warn_explicit
</pre>
The following signatures differ between versions:
<pre>
    - traitlets.config.application.Application.generate_config_file(self)
    + traitlets.config.application.Application.generate_config_file(self, classes='None')

    - traitlets.config.application.catch_config_error(method, app, *args, **kwargs)
    + traitlets.config.application.catch_config_error(method)

    - traitlets.config.configurable.Configurable.class_config_section()
    + traitlets.config.configurable.Configurable.class_config_section(classes='None')

    - traitlets.config.configurable.Configurable.class_get_trait_help(trait, inst='None')
    + traitlets.config.configurable.Configurable.class_get_trait_help(trait, inst='None', helptext='None')

    - traitlets.config.loader.ArgParseConfigLoader.load_config(self, argv='None', aliases='None', flags='None')
    + traitlets.config.loader.ArgParseConfigLoader.load_config(self, argv='None', aliases='None', flags='None', classes='None')

    - traitlets.traitlets.Dict.element_error(self, obj, element, validator)
    + traitlets.traitlets.Dict.element_error(self, obj, element, validator, side='Values')

    - traitlets.traitlets.HasDescriptors.setup_instance(self, *args, **kwargs)
    + traitlets.traitlets.HasDescriptors.setup_instance(*args, **kwargs)

    - traitlets.traitlets.HasTraits.setup_instance(self, *args, **kwargs)
    + traitlets.traitlets.HasTraits.setup_instance(*args, **kwargs)

    - traitlets.traitlets.TraitType.error(self, obj, value)
    + traitlets.traitlets.TraitType.error(self, obj, value, error='None', info='None')
</pre>
The following attribute seem new, but we are not too sure,
(They might be new inherited attributes, or stuff we don't handle yet)
<pre>
    + traitlets.config.application.Application.emit_alias_help
    + traitlets.config.application.Application.emit_description
    + traitlets.config.application.Application.emit_examples
    + traitlets.config.application.Application.emit_flag_help
    + traitlets.config.application.Application.emit_help
    + traitlets.config.application.Application.emit_help_epilogue
    + traitlets.config.application.Application.emit_options_help
    + traitlets.config.application.Application.emit_subcommands_help
    + traitlets.config.application.Application.show_config
    + traitlets.config.application.Application.show_config_json
    + traitlets.config.application.Application.start_show_config
    + traitlets.config.application.Application.trait_defaults
    + traitlets.config.application.Application.trait_has_value
    + traitlets.config.application.Application.trait_values
    + traitlets.config.configurable.Configurable.trait_defaults
    + traitlets.config.configurable.Configurable.trait_has_value
    + traitlets.config.configurable.Configurable.trait_values
    + traitlets.config.configurable.LoggingConfigurable.trait_defaults
    + traitlets.config.configurable.LoggingConfigurable.trait_has_value
    + traitlets.config.configurable.LoggingConfigurable.trait_values
    + traitlets.config.configurable.SingletonConfigurable.trait_defaults
    + traitlets.config.configurable.SingletonConfigurable.trait_has_value
    + traitlets.config.configurable.SingletonConfigurable.trait_values
    + traitlets.config.loader.LazyConfigValue.trait_defaults
    + traitlets.config.loader.LazyConfigValue.trait_has_value
    + traitlets.config.loader.LazyConfigValue.trait_values
    + traitlets.traitlets.Any.default
    + traitlets.traitlets.Any.subclass_init
    + traitlets.traitlets.BaseDescriptor.subclass_init
    + traitlets.traitlets.Bool.default
    + traitlets.traitlets.Bool.subclass_init
    + traitlets.traitlets.Bytes.default
    + traitlets.traitlets.Bytes.subclass_init
    + traitlets.traitlets.CBool.default
    + traitlets.traitlets.CBool.subclass_init
    + traitlets.traitlets.CBytes.default
    + traitlets.traitlets.CBytes.subclass_init
    + traitlets.traitlets.CComplex.default
    + traitlets.traitlets.CComplex.subclass_init
    + traitlets.traitlets.CFloat.default
    + traitlets.traitlets.CFloat.subclass_init
    + traitlets.traitlets.CInt.default
    + traitlets.traitlets.CInt.subclass_init
    + traitlets.traitlets.CRegExp.default
    + traitlets.traitlets.CRegExp.subclass_init
    + traitlets.traitlets.CUnicode.default
    + traitlets.traitlets.CUnicode.subclass_init
    + traitlets.traitlets.Callable.default
    + traitlets.traitlets.Callable.subclass_init
    + traitlets.traitlets.CaselessStrEnum.default
    + traitlets.traitlets.CaselessStrEnum.info_rst
    + traitlets.traitlets.CaselessStrEnum.subclass_init
    + traitlets.traitlets.ClassBasedTraitType.default
    + traitlets.traitlets.ClassBasedTraitType.subclass_init
    + traitlets.traitlets.Complex.default
    + traitlets.traitlets.Complex.subclass_init
    + traitlets.traitlets.Container.default
    + traitlets.traitlets.Container.subclass_init
    + traitlets.traitlets.DefaultHandler.subclass_init
    + traitlets.traitlets.Dict.default
    + traitlets.traitlets.Dict.subclass_init
    + traitlets.traitlets.DottedObjectName.default
    + traitlets.traitlets.DottedObjectName.subclass_init
    + traitlets.traitlets.Enum.default
    + traitlets.traitlets.Enum.info_rst
    + traitlets.traitlets.Enum.subclass_init
    + traitlets.traitlets.EventHandler.subclass_init
    + traitlets.traitlets.Float.default
    + traitlets.traitlets.Float.subclass_init
    + traitlets.traitlets.ForwardDeclaredInstance.default
    + traitlets.traitlets.ForwardDeclaredInstance.subclass_init
    + traitlets.traitlets.ForwardDeclaredType.default
    + traitlets.traitlets.ForwardDeclaredType.subclass_init
    + traitlets.traitlets.HasTraits.trait_defaults
    + traitlets.traitlets.HasTraits.trait_has_value
    + traitlets.traitlets.HasTraits.trait_values
    + traitlets.traitlets.Instance.default
    + traitlets.traitlets.Instance.subclass_init
    + traitlets.traitlets.Int.default
    + traitlets.traitlets.Int.subclass_init
    + traitlets.traitlets.List.default
    + traitlets.traitlets.List.subclass_init
    + traitlets.traitlets.ObjectName.default
    + traitlets.traitlets.ObjectName.subclass_init
    + traitlets.traitlets.ObserveHandler.subclass_init
    + traitlets.traitlets.Set.default
    + traitlets.traitlets.Set.subclass_init
    + traitlets.traitlets.TCPAddress.default
    + traitlets.traitlets.TCPAddress.subclass_init
    + traitlets.traitlets.This.default
    + traitlets.traitlets.This.subclass_init
    + traitlets.traitlets.TraitType.default
    + traitlets.traitlets.TraitType.subclass_init
    + traitlets.traitlets.Tuple.default
    + traitlets.traitlets.Tuple.subclass_init
    + traitlets.traitlets.Type.default
    + traitlets.traitlets.Type.subclass_init
    + traitlets.traitlets.Unicode.default
    + traitlets.traitlets.Unicode.subclass_init
    + traitlets.traitlets.Union.default
    + traitlets.traitlets.Union.subclass_init
    + traitlets.traitlets.UseEnum.default
    + traitlets.traitlets.UseEnum.info_rst
    + traitlets.traitlets.UseEnum.subclass_init
    + traitlets.traitlets.ValidateHandler.subclass_init
    + traitlets.traitlets.directional_link.link
    + traitlets.traitlets.link.link
</pre>
The following attribute seem to have been removed:
(They might have been inherited attributes, or stuff we didn't handle then)
<pre>
    - traitlets.traitlets.List.element_error
    - traitlets.traitlets.Set.element_error
    - traitlets.traitlets.Tuple.element_error
</pre>
</details>

**Comment by Carreau** [comment]
Ok, let's move on and try to get a beta1.

**Comment by rmorshea** [comment]
@Carreau thank you for putting so much effort into getting 5.0 out! This will make it so much easier to maintain `traitlets` going forward. I just wish I had the time to help you out.

**Comment by Carreau** [comment]
No problem, you did most of the work during the past few years !

There hasn't been many complaints, is no objections I'll do a RC1 on friday.

**Comment by opoplawski** [comment]
So, there is a pypi release but no github tag?  What's up?

**Comment by Carreau** [comment]
Oh, I pushed the commit for forgot to push the tag, it is pushed no, Both commit and tag should be GPG signed.

Thanks for catching that.

**Comment by rmorshea** [comment]
Seems like we can close this now that 5.0 is out! Discussion about bugs in 5.x can continue here https://github.com/ipython/traitlets/issues/564
