### ISSUE TITLE
ProxyTrait

### ISSUE THREAD

**Issue by rmorshea** [ipython/traitlets#423]
*I don't have time to make a complete PR right now*

# Summary

A simple class, whose subclasses can wrap an arbitrary trait with extra logic.

# Use Case

Imagine if you needed to run certain logic after all the observers of a given trait have fully propagated their changes. This is not possible through observance in traitlets because the order in which callbacks are gathered and fired is not publically known. However, you could accomplish this with a proxy that calls a trait's `TraitType.set` method before its own.

# Implementation

```python
class TraitProxy(TraitType):

    def __init__(self, trait):
        self.__trait = trait

    def instance_init(self, obj):
        self.__trait.instance_init(obj)

    def class_init(self, cls, name):
        self.__trait.class_init(cls, name)

    def set(self, obj, val):
        self.__trait.set(obj, val)

    def get(self, obj, cls):
        return self.__trait.get(obj, cls)

    def __getattr__(self, name):
        return getattr(self.__trait, name)
```

# Example

```python
class Perishable(ProxyTrait):

    def set(self, obj, cls):
        super(Perishable, self).set(obj, cls)
        obj.mark_as_stale()

class MyClass(HasTraits):

    i = Perishable(Int())
    j = Int()
    
    @observe("i")
    def _i_changed(self, change):
        self.j = change.new
    
    def mark_as_stale(self):
        # do something after the object has been fully updated.
        assert self.i == self.j
```

**Comment by minrk** [comment]
I'd like to have a real, currently existing use case in actively used code where this problem exists before implementing something like this. This should be a barrier for *all* changes to traitlets: it must address problems people are already facing.
