### ISSUE TITLE
Linking list with tuple: Appending list does not update tuple.

### ISSUE THREAD

**Issue by OliverEvans96** [ipython/traitlets#443]
If a list is linked to a tuple, then appending the list does not update the tuple. However, redefining the list does.

```python
In [1]: from traitlets import *
   ...: from ipywidgets import *
   ...: 
   ...: class MyTrait(HasTraits):
   ...:     l = List()
   ...:     t = Tuple()
   ...: 
   ...: m1 = MyTrait()
   ...: m2 = MyTrait()
   ...: 
   ...: link1 = link((m1, 'l'), (m2, 'l'))
   ...: link2 = link((m1, 'l'), (m2, 't'))
   ...: m1.l.append('test')
   ...: 

In [2]: m2.l
Out[2]: ['test']

In [3]: m2.t
Out[3]: ()

In [4]: m1.l = ['Totally new list']

In [5]: m2.l
Out[5]: ['Totally new list']

In [6]: m2.t
Out[6]: ('Totally new list',)
```

It would be nice for appending the list to update the tuple. Is there a way to manually trigger this?

Thanks,
Oliver

**Comment by rmorshea** [comment]
There is currently no way to track changes that an instance held by a trait undergoes.

https://github.com/jupyter-widgets/ipywidgets/pull/1071 is a downstream proposal which may eventually make its way back into traitlets when it has proven top be stable enough.

**Comment by OliverEvans96** [comment]
Thanks @rmorshea!

**Comment by rmorshea** [comment]
For tracking changes to mutable data types I recommend using https://github.com/rmorshea/spectate. Traitlets was never really designed to be able to do this.
