### ISSUE TITLE
Traitful class attribute?

### ISSUE THREAD

**Issue by OliverEvans96** [ipython/traitlets#444]
Hi all,

Traitlets is great for instance attributes which can notify on value changes. Can anyone think of a way to have a class attribute with the same behavior? i.e., a traitlet which is shared among all members of a class, and the class type itself.

Thanks,
Oliver

**Comment by minrk** [comment]
I don't think traitlets supports any kind of traited class attribute, sorry.

**Comment by rmorshea** [comment]
@OliverEvans96, one would need to define a "trait" on a metaclass in order to see the same behavior. That's not something traitlets was designed for.
