### ISSUE TITLE
Reference to HasTraits object inside the contained Trait object?

### ISSUE THREAD

**Issue by anglosasso** [ipython/traitlets#454]
This is not really an issue, more like a general question.
I am creating a small module for generating Qt controllers to control traits corresponding to parameters in an interface. I would have a new trait inside the controller object linked to the original one, something like:

```python
import traitlets as tr

class FirstClass(tr.HasTraits):
    i = tr.Integer(5, min=3, max=5)


class SecondClass(tr.HasTraits):
    j = tr.Integer()

    def __init__(self, has_traits_obj, name):
        tr_obj =  has_traits_obj.traits()[name]

        for k in tr_obj.metadata.keys():
            self.traits()['j'].set_metadata(k, tr_obj.metadata[k])
        tr.link((has_traits_obj, name), (self, 'j'))
        
        
first_obj = FirstClass()
second_obj = SecondClass(first_obj, 'i')
```

In doing this, I realized that I cannot instantiate the controller from the Trait object alone because there is no reference to its HasTraits object container, only to the class. 

```python
# I would like to have instead
second_obj = SecondClass(first_obj.traits()['i'])
# But I don't find reference to first_obj in first_obj.traits()['i']
```

Obviously I can work around it passing the (HasTraits, 'name') tuple, but the point is: why not allowing to link from the Trait object alone by having in it a reference to the HasTraits object which contains it? This may be a naive question - is there some general conceptual error I am making here?

**Comment by rmorshea** [comment]
This is, unfortunately, a conceptual error. Check out this introduction to [descriptors](https://www.ibm.com/developerworks/library/os-pythondescriptors/index.html), which my give you some more detailed insight into why having a reference to objects on a descriptor doesn't work out.

In short though, consider three facts:

1. Traits are class attributes (that is, they are owned by the class).
2. One class can have many instances (or objects).
3. All instances reference the same class attributes (that is, they don't own them).

All this implies that a single trait is associated with **all** instances of a class, and thus is "owned" by no single instance. Thus, the idea of associating a trait with any one object that may reference it, is a bit contradictory.

**Comment by anglosasso** [comment]
@rmorshea Yeah I was expecting that! Thank you very much for the answer and the reference.
