### ISSUE TITLE
A proper way to do embeded HasTrait?

### ISSUE THREAD

**Issue by zsluedem** [ipython/traitlets#476]
Is there a proper way to do the embeded Hastrait. Here is what I think

Here is one object has-traits.
```python
class Foo(HasTraits):
    value = Int()
```

I want to implement another object that has a trait 'Foo'

```python
class Foo2(HasTraits):
    value2 = Foo()
```

But it doesn't check the type at all.

So I have to do a middle TraitType like that

```python
class FooTrait(TraitType):
        def validate(self, obj, value):
        if not isinstance(value, Foo):
            raise TypeError
        return value
```

Is it the proper way to implement the embeded traitlets?

**Comment by ankostis** [comment]
```python
class Foo2(HasTraits):
    value2 = Instance(Foo)
```

**Comment by zsluedem** [comment]
@ankostis thanks. I found that too

**Comment by ankostis** [comment]
Now, that was simple.

What's more complicated is to make `Foo2` a subclass of `Configurable`, 
and implicitly modify values, by loading *configurations* into the "hierarchy".
For this to work, you have to set the `parent` property.  

A more descriptive code is given below to exemplify this case:

```python
from traitlets import *
from traitlets.config import *
   
class Bar(Configurable):
    num = Int().tag(config=True)

class Foo(Configurable):
    mybar = Instance(Bar).tag(config=True)

## Build the configuration
#
c = Config()
c.Foo.Bar.num = 3  # The more specific value applies.
c.Bar.num = 1      # Would apply if above was missing.

## Build and configure the hierarchy.
#
f = Foo(config=c)
f.mybar = Bar(parent=f)
assert f.mybar.num == 3
```

Note that child-assignment must happen AFTER parent has loaded config:
```python
f = Foo()
f.mybar = Bar(parent=f)
f.config = c    # Too late to apply to child.
assert f.mybar.num == 0
```

...or else, you need to apply it specifically to child:
```python
f = Foo()
f.mybar = Bar(parent=f)
f.mybar.config = c
assert f.mybar.num == 3
```
..of course you can set your code to *observe* the `config` param and update child's `config`,
but we are entering too deep into details now.

**Comment by zsluedem** [comment]
@ankostis Wow, that is really helpful~! I really appreciate it~! Thanks a lot~!
