### ISSUE TITLE
Build on Master is Failing

### ISSUE THREAD

**Issue by rmorshea** [ipython/traitlets#497]
@minrk the build is currently failing:

[![Build Status](https://travis-ci.org/ipython/traitlets.svg?branch=master)](https://travis-ci.org/ipython/traitlets)

It seems like the most recent versions of `jupyter/notebook` and `jupyter-widgets/traittypes` haven't been released yet. The former is missing a test dependency for `selenium` and the latter is attempting to import `Sentinel` from `traitlets` which is no longer included in `__all__`. Both of these  issues appear to have been fixed in their respective master branches.

**Comment by SylvainCorlay** [comment]
@rmorshea the latter was fixed in `traittypes` but is not yet in a release,

**Comment by minrk** [comment]
Tests are passing other than what appear to be real failures in traittypes
