### ISSUE TITLE
bug in setting default_value in subclasses of Instance 

### ISSUE THREAD

**Issue by lurgyman63** [ipython/traitlets#504]
The following snippet gives unexpected behavior:

```python
>>> import traitlets as tl
>>> tr = tl.List(trait=tl.Unicode(), default_value=['hi'])
>>> print('tr default is ', tr.default_value)
tr default is  traitlets.Undefined
```
I'd expect the output to be `tr default is ['hi']`, since that was the requested default_value.

It looks to me like the error is in traitlets.py in `Instance.__init__`. A fix could be changing

`super(Instance, self).__init__(**kwargs)`

to

`super(Instance, self).__init__(*args, **kwargs)`

(or alternately its subclasses could set `kwargs['default_value'] = default_value` instead of passing via `args`).

**Comment by rmorshea** [comment]
Is this a duplicate of https://github.com/ipython/traitlets/issues/455?

**Comment by lurgyman63** [comment]
Ah yes, you’re right - thanks. I apologize for not finding that. Looks like
current master should fix this bug. Has a release with this fix been made
yet?

**Comment by rmorshea** [comment]
@lurgyman63 I don't think a fix has been made for this. I don't know how easy it would be to change this, but feel free to review the issue and give it a go. I'm happy to try and review anything you might propose.

**Comment by rmorshea** [comment]
Closing this in favor of #455.
