### ISSUE TITLE
PYPI metadata requires_dist

### ISSUE THREAD

**Issue by fizwit** [ipython/traitlets#506]
please update requieres_dist metadata on Pypi. The package name ipython-genutils should use an underscore.  change to ipython_genutils

**Comment by rmorshea** [comment]
@fizwit thanks for pointing this out. Turns out use of `ipython_genutils` should be dropped anyway:

https://github.com/ipython/traitlets/issues/511

If you're able to open a PR to fix this that would be amazing!
