### ISSUE TITLE
Use Parent Log If Exists

### ISSUE THREAD

**Issue by travigd** [ipython/traitlets#514]
I'd like to see the default `log` attribute of a `LoggingConfigurable` be the parent log, rather than the global traitlets log, if the parent is also a LoggingConfigurable.

```python
class LoggingConfigurable(...):
    ...

    log = Instance('logging.Logger')
    @default('log')
    def _log_default(self):
        # (vvv) new behavior (vvv)
        if isinstance(self.parent, LoggingConfigurable):
            return self.parent.log
        # (^^^) new behavior (^^^)
        from traitlets import log
        return log.get_logger()
```

If that sounds okay I can open a merge request with those two lines added.

**Comment by travigd** [comment]
The "workaround" is just to add `log=self.log` wherever you use `parent=self`, but I'd argue that using the parent log should be the expected behavior (especially when you have two disparate sets of code that use traitlets).

I basically discovered this when I wrote a small library that uses traitlets and then an application that uses traitlets that also uses the library. So I have code that looks something like
```python
client = my_library.ApiClient(log=self.log.getChild("my_library"))
```
and was confused when I wasn't seeing all of the expected logs from traitlets instances that were children of the `client` object.

**Comment by minrk** [comment]
Makes sense to me, feel free to make that PR.
