### ISSUE TITLE
New 4.3.3 Release

### ISSUE THREAD

**Issue by rmorshea** [ipython/traitlets#530]
An issue for tracking the progress to a 4.3.3 release.

I have created a 4.3.x branch. In order to get a release, make a PR against this branch with changes that you would like to see included. Be sure to link to the commits your are cherry picking when you make a PR.

**Comment by kevin-bates** [comment]
Thank you for creating this 4.3.x placeholder.  Before I go down the road of adding the contents of #522 (which depends on #341), I see that #341 (and perhaps commits on which it may depend) is marked for milestone `5.0`.  This implies it contains an API-level change warranting a major release.  As a result, I'm hesitant to backport that PR to the 4.3.3 release.

If we find that 5.0 is more warranted, I think that may be more straightforward than cherry-picking specific commits - especially when multi-commit PRs aren't squashed.  Of course, I also see milestones of `5.1` that would need to be discarded from 5.0 or we determine they can be included.

Thoughts?

**Comment by kevin-bates** [comment]
Hi Ryan,

I've gone ahead and composed a PR (#532) that cherry picks only a portion of the commit on which #522 depends.  This way, no API or milestone-triggering changes take place.  I also included a couple more generic commits relative to versioning and travis.

I hope this is the kind of thing you're looking for relative to getting 4.3.3 (or 4.4.0) released.

Thanks for your help.

**Comment by rmorshea** [comment]
@kevin-bates I'd like to get some feedback from @minrk on this, but my guess is that small releases will be ideal. There's just so much stuff that belongs in a 5.0 release, and I simply don't have the bandwidth to manage that at the moment.

**Comment by kevin-bates** [comment]
@rmorshea - ping on `4.3.3` tag - thanks.

**Comment by rmorshea** [comment]
@kevin-bates done:

https://pypi.org/project/traitlets/4.3.3.dev0/

**Comment by kevin-bates** [comment]
@rmorshea - thank you!

Could you please share under what criteria a formal `4.3.3` gets generated?  I'd like to get an idea of the timeframe since I may need to create an interim release that requires `4.3.3.dev0` if we're talking about months.

**Comment by rmorshea** [comment]
@kevin-bates in the absence of input from @minrk, @ellisonbg, @Carreau, @SylvainCorlay, @jasongrout or anyone else with more context for the impact a mainline release might have, I don't have a definitive set of criteria. The change seems small enough that it wouldn't be a problem, but it'd be good to get a quick sign-off from a core dev since most Jupyter packages that depend on traitlets don't have their versions pinned.

**Comment by minrk** [comment]
If it unblocks things, I'm happy to make 4.3.3 with just #532 backported. There's a lot in master for 5.0 and some of it (mainly the new argparse/env string parsing) that needs to be finished before a major release can be made, since it's in an incomplete/unreleasable state right now.

I'm really sorry this has stalled so much.

**Comment by kevin-bates** [comment]
That would be awesome @minrk, thank you!

**Comment by minrk** [comment]
4.3.3 published from the 4.3.x branch

**Comment by rmorshea** [comment]
Thanks @minrk
