### ISSUE TITLE
Non Singleton Application Class

### ISSUE THREAD

**Issue by Zsailer** [ipython/traitlets#534]
I'd like to propose adding a non-singleton Application class. 

Right now, Application classes are strictly singleton. This strict requirement is causing me issues over in the [jupyter_server](https://github.com/jupyter/jupyter_server) world. I've been working on creating an `ExtensionApp` abstraction in jupyter_server that's a subclass of `Application`. This object starts a Jupyter Server and adds extra endpoints+config. The problem is that the Jupyter Server object is also an instance of the `Application` class, so I get "multiple instances of a singleton" errors. 

The `ExtensionApp` object behaves, in every way, like an application object:
* launched from CLI, parse command line
* load config from CLI and file
* uses methods like initialize, start, stop, etc. 
So, I'd like to inherit 90% of the functionality from the Application class. 

I'm wondering if we can create a mixin (or something else) that separates the non-singleton  from the singleton-needed properties+methods. I think the main reason applications were made singleton was to enforce a central logging system? Fortunately, the `ExtensionApp` object shares the logging system with the underlying server application.

**Comment by rmorshea** [comment]
@Zsailer my intuition says that the easiest way to do this would be to make the application class a singleton, by default, but with the option to subclass it where `singleton=False`. However I haven't worked with the application in a long time so it'd be hard for me to really tell whether there would be any adverse side effects if you simply allowed applications to have multiple instances.

**Comment by rmorshea** [comment]
I'm certainly open to reviewing a PR, but unfortunately I don't really have time to write one up myself.

**Comment by Zsailer** [comment]
Oh for sure. Thanks, @rmorshea. If I come up with a PR, I'll definitely ping you. 

My immediate thought was that it might be dangerous to have an option to shut off the singleton class property inherited from singleton parent classes. Wouldn't this affect all instances of all subclasses? Some of these classes might still check for singleton behavior and get unexpected results... 

That's what made me consider making an `ApplicationBase` class that is inherited by the singleton `Application` class. That won't affect any other classes, and this Application Base can be inherited in instances when singleton enforcment isn't necessary.

**Comment by rmorshea** [comment]
@Zsailer so looking at the code, you should be able to make multiple application instances so long as you don't use `Application.instance(*args, **kwargs)` to create them simple instantiate them as you would any other class (i.e. `Application(*args, **kwargs)`). Have you tried this?

**Comment by rmorshea** [comment]
Based on last comment, it seems like this is resolved.
