### ISSUE TITLE
SyntaxWarning: "is" with a literal. Did you mean "=="?

### ISSUE THREAD

**Issue by bh2smith** [ipython/traitlets#553]
I've been getting the following error when opening `ipython`

```
/usr/local/Cellar/ipython/7.14.0/libexec/vendor/lib/python3.8/site-packages/traitlets/config/loader.py:795: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if len(key) is 1:
```

I attempted to link the exact line of code from `traitlets/config/loader.py:795:` on but it doesn't appear to be there. Perhaps this has already been addressed, but I tried upgrading and, at least, ipython is already "latest" according to brew.

**Comment by dtrodrigues** [comment]
This was fixed by https://github.com/ipython/traitlets/pull/551 but a new version of traitlets has not been released for ipython to use in its homebrew formula.

**Comment by bh2smith** [comment]
Thanks for getting back, I'll look forward to the next release!
