### ISSUE TITLE
Downstream testing of 5.x/master

### ISSUE THREAD

**Issue by Carreau** [ipython/traitlets#564]
In order to have some confidence that tratilets master does nto break too many things it would be great to have it tested in a couple  of downstream projects. 

Here is a list of issues/PRs that do so: 

- https://github.com/jupyterhub/jupyterhub/pull/3076
- https://github.com/ipython/ipython/pull/12370
- https://github.com/jupyter-widgets/ipywidgets/issues/2898

Are you users of traitlets ? Are you hoping for a 5.x release ? If so please test with traitlets master on your project and past a link to your project below. Thanks !

You do not maintain a project that uses traitlets ? Please install master on your local environement if you can and let us know if you encounter any issues.

**Comment by nklever** [comment]
I would expect that getattr(config, trait) would return the value (or default_value) of the trait, either if it exist or not. But currently (either 4.3.3 and 5.0.0) it would only return the value if it exists and returns an instance of LazyConfigValue if it does not exists. 
To demonstrate this behaviour I'm attaching an example including a workaround to solve this behaviour in a second step of including an if-clause to simply check for a LazyConfigValue instance.
[TraitletsTest.zip](https://github.com/ipython/traitlets/files/4746528/TraitletsTest.zip)

**Comment by Carreau** [comment]
I'm not quite sure if this is fixable. When you load  the configuration you do not yet know what the values it will take, not if it will exists, so the only thing `getattr` can give you when not value has been set is a `LazyConfigValue`. 

like if you do `c.Application.foo.add('123')` then the default value of `config['foo']` will depends on wether you apply this config to `TestVarsApp` or `TestThisApp`. You've seen it yourself as your `if workaround` uses the current class to decide how to reify. 

This is made harder as traitlets support `c.Class1.Class2.value`. 

I'm also curious how you are using it. In most case you should not have to inspect the config object and pass it around your classes and it will configure the class attributes as long as they are instance of `Configurable`.

**Comment by nklever** [comment]
Maybe I'm understanding something wrong, but my understanding of the **default_value** in the definition of traits was, to use this value also, if it does not be configured directly in a configuration. This was my intention in inspecting the config object, to use it for all traits in a class - either for the configured but also for the unconfigured, but with default_values defined trait variables in a class. Am I wrong in using it that way ? And - you are right - I didn't considered things like c.Class1.Class2.value.

**Comment by Carreau** [comment]
Say you have the following:
```
from traitlets import Configurable, Integer, Config

class Base(Configurable):
    pass

class Derive(Base):
    myval = Integer(default_value=99).tag(config=True)

class MegaDerive(Derive):
    myval = Integer(default_value=42).tag(config=True)


class OtherDerive(Base):
    myval = Integer(default_value=12).tag(config=True)
```
In an "empty" config, what is the value of `c.Base.myval` ? 99, 42, or 12 ? 
In an "empty" config, what is the value of `c.Derive.myval` ? 99, 42 ? 
In an "empty" config, what is the value of `c.OtherDerive.myval` ? 12 is the only solution right ? Well, no because I have another `class HiddenDerive(OtherDerive):` !

A default config value only make sens when applied to a known class.

**Comment by nklever** [comment]
Ok, I think there's some missunderstanding - it's clear to know what class should be used in a certain environment. Adding the following code to your example:

    class testApp(Application):
        pass
    
    a = testApp()
    d = Derive()
    m = MegaDerive()
    o = OtherDerive()
    
    a.config.Derive.myval=d.myval
    print(a.config)
    print(m.myval)
    a.config.MegaDerive.myval = getattr(a.config.MegaDerive, "myval", m.myval)
    print(a.config)

you get 

    {'Derive': {'myval': 99}}
    42
    {'Derive': {'myval': 99}, 'MegaDerive': {'myval': <LazyConfigValue {}>}}

but I would expect

    {'Derive': {'myval': 99}, 'MegaDerive': {'myval': 42}}

because of the optional default of getattr.

**Comment by Carreau** [comment]
I'm sure I had a response written yesterday but I don't see it today and it's not in draft... so meh. 

I'm really trying to understand  what you are trying to achieve, and why you are poking at config objects directly instead of doing `Derive(config=config)`. 

Like really you should not do that this is not how traitlets are meant to be used. But I can give you the benefit of the doubt that you have a use case.

Also it's usually not because in some subset of cases you _can_ do something that it is possible to detect those case, and even less do the right thing in the general case. 

In your above example you use `getattr(a.config.MegaDerive, "myval")` python has absolutely no idea what you are going to do with the result.

It is strictly equivalent to  `a.config.MegaDerive.myval` from python execution model. If we were to return `None` in that case, it would be completely impossible to have `a.config.MegaDerive.myval.add(...)` to work, that would raise  `AttributeError: 'NoneType' object has no attribute "add"`. 
And this is one of the cornerstone of how you wrote traitlets config objects with `c.`

One of the requirement to make what you ask possible would be made to know ahead of time all the possible classes and attributes that can be configured and validate them while the config is built, which by definition of loading configuration before instantiating the application is impossible.


So you are kind of telling me that you want to read a book which main character has the same eye color of the reader, but you explicitly want me to tell you which color this is, but don't want to tell me who is going to read the book.

It's not possible.


Finally I think we are going away from the reason for this issue which is does master break usage. And this is unrelated, so it would be nice to move this to a separate issue.

**Comment by vidartf** [comment]
Interesting to see some movement on traitlets 5.0! Thanks for doing this ❤️  I see the updated changelog in the docs, but I wonder if it would be possible to separate the entries into breaking / non-breaking changes? That way, it would be easier to test different packages / scenarios in an informed manner 😺

**Comment by vidartf** [comment]
CC @Zsailer since he has been working a lot with traitlets in the jupyter_server code, and @jupyter-widgets for use in ipywidgets.

**Comment by azjps** [comment]
A small data point but I've been using the master branch of `traitlets` (last updated earlier this year) for a few private projects, in order to use some of the CLI-related changes.

One minor issue I've encountered and locally patched was the [hiding of some of the API that was exposed in `traitlets` 4.x](https://github.com/ipython/traitlets/pull/546) but which are still used in some 3rd party projects, for example [`qgrid` currently imports `parse_notifier_name` from `traitlets.py`](https://github.com/quantopian/qgrid/blob/d5240d553ac1f90479555ee56606bf5d6bce2b74/qgrid/grid.py#L19) but it is now hidden.

**Comment by Carreau** [comment]
Thanks, I'll try to re-export that before releasing.

**Comment by rmorshea** [comment]
Actually seems like people have been posting new issues. Can close this general discussion ticket too I think.
