### ISSUE TITLE
Priority in notifications?

### ISSUE THREAD

**Issue by zerline** [ipython/traitlets#581]
**Is their a way to set priorities between notifications, for example a link and an observer?**

----
Hi

sage_combinat_widgets is a set of widgets to represent mathematical objects graphically and interactively. Until now, all the widgets are grid-like, with individual elements, or `cells`, as buttons or text inputs.

Here is one of the example notebooks. Set up `dominos` on a graph, then implement an algorithm to flip all the dominos. This is what you can see on:

https://mybinder.org/v2/gh/sagemath/sage-combinat-widgets/develop?filepath=examples/FlippingDominos.ipynb

Yet to be able to reproduce this algorithm manually is the way mathematicians would like to explore things on widgets. And this task has been tough.

In the python code (https://github.com/sagemath/sage-combinat-widgets/blob/develop/examples/dominos/flipping_dominos.py), there's a method called `set_cell()` with an observer on it. This method is called whenever a cell is  pressed on the notebook. A flip happens when 2 neighboring dominos are pressed. The difficult issue is a conflict between the domino link (that links 2 cells to each other to make up a domino) and the notifications made by the observer, leading to infinite loops. Things would be easier if the domino link could take effect _before_ the observed method is called. But the domino link only does its job after the observed method is done entirely.

How priorities are they dealt with? Is there a way for users to decide on their own priorities?

**Comment by rmorshea** [comment]
I think it would be easier to understand what your asking for if you could provide a minimal example of your use case.

**Comment by rmorshea** [comment]
Feel free to re-open, but I'm going to close for now.
