### ISSUE TITLE
consider allowing logging.LoggingAdapter to be a LoggingConfigurable.log

### ISSUE THREAD

**Issue by akhmerov** [ipython/traitlets#606]
Sphinx uses `logging.LoggingAdapter` as its own logger, while nbconvert classes all inherit from traitlets `LoggingConfigurable`, and require the `log` trait to be a `logging.Logger`. This prevents passing sphinx logger to nbconvert classes. At the same time, docs [state](https://docs.python.org/3/library/logging.html#logging.LoggerAdapter):

> ...These methods have the same signatures as their counterparts in Logger, so you can use the two types of instances interchangeably.

**Comment by Carreau** [comment]
I think it make sense but that might be too much of a refactor for 5.0, I think we can make it for 5.1, I expect 5.0 to break some stuff anyway, and as 5.0 is still API compatible (hopefully) with 4.3 using this functionality would mean requiring 5.0+ for project. 

The core of the difficulty is that `Instance` has a `klass` attribute which is use both in context where a tuple would work (`isinstance(value, self.class)`) but also to instantiate values `self.klass(params)`, so we can likely have a private version that relax those constraint for LoggingConfigurable, but we would have to be careful.

**Comment by akhmerov** [comment]
Gotcha, thanks for the explanation.

**Comment by akhmerov** [comment]
If some desperate soul comes to this issue in search of a workaround, I think this should work:

```python
from logging import Logger
class LoggerWrapper(Logger):
    def __init__(self, wrapped):
        self._wrapped = wrapped

    def __getattr__(self, attr):
        attr = self._wrapped.__getattribute__(attr)

logger = LoggerWrapper(my_logger_adapter)
```

**Comment by minrk** [comment]
I believe the only assumption broken by LoggerAdapter we have is in setting [Application.log_format](https://github.com/ipython/traitlets/blob/2f22fb7069859411c12f9817bd622875f11444d9/traitlets/config/application.py#L202) we modify `self.log.handlers[0]` and `handlers` is not one of the passthrough properties on LoggerAdapter.

so we could either explicitly allow LoggerAdapter and handle `self.log.logger.handlers...` or try to be even looser somehow. #619 seems to work
