### ISSUE TITLE
Passing None on the command line

### ISSUE THREAD

**Issue by maartenbreddels** [ipython/traitlets#612]
cc @SylvainCorlay 

Hi all,

congrats with the 5.0 release! But with all big releases come bugs :)

In voila we used to pass to a Unicode config a None value by using
```
$ voila --template=None
```
With traitlets 5, this becomes the string 'None'. Any falsy would work for us, but it also does not seem possible to pass an empty string.

Any ideas for workaround, or would this require a fix?

cheers,

Maarten

Related voila PR: https://github.com/voila-dashboards/voila/pull/691

**Comment by SylvainCorlay** [comment]
cc @minrk 

I am not so familiar with the changes in the Configurable, but tis is breaking some downstream package CIs.

**Comment by minrk** [comment]
Thanks for testing! Should be fixed by #613

**Comment by minrk** [comment]
FWIW, this is solvable with custom traits which can define `from_string` for arbitrary logic when handling casting from cli string to actual value. This is not overrideable via tags on existing traits, but perhaps it should be. Until we do that, you have to define custom traits to override from_string:

```python
class MyUnicode(Unicode):
    def from_string(s):
        if s == "None":
            return None
        return s
```

**Comment by maartenbreddels** [comment]
Hmm, it's a bit hidden in voila, but I pass extra arguments via a test:
```
    return ['--template=', '--VoilaTest.template_paths=[%r, %r]' % (path_test_template, path_default), '--VoilaExecutor.timeout=240']
```

And later on I find that:
```
(Pdb++) self.voila_configuration.template
''
(Pdb++) repr(self.voila_configuration.template)
"''"
```

**Comment by maartenbreddels** [comment]
Excuse my lack of caffeine, this is just a double repr! It should work then!
