### ISSUE TITLE
Traitlets 5 uses f-strings in code, not compatible with Python 3.5

### ISSUE THREAD

**Issue by haosong-didi** [ipython/traitlets#620]
### Issue Description
I use Python 3.5, and when I "pip3 install notebook" for Jupyter notebooks, latest version traitlets (5.0.3) got installed, which uses f-string syntax in some code, resulting in a failure when I try to launch a Jupyter notebook server.
```
$ jupyter notebook
Traceback (most recent call last):
  File "/home/luban/.local/bin/jupyter-notebook", line 7, in <module>
    from notebook.notebookapp import main
  File "/home/luban/.local/lib/python3.5/site-packages/notebook/__init__.py", line 27, in <module>
    from .nbextensions import install_nbextension
  File "/home/luban/.local/lib/python3.5/site-packages/notebook/nbextensions.py", line 26, in <module>
    from .config_manager import BaseJSONConfigManager
  File "/home/luban/.local/lib/python3.5/site-packages/notebook/config_manager.py", line 14, in <module>
    from traitlets.config import LoggingConfigurable
  File "/home/luban/.local/lib/python3.5/site-packages/traitlets/__init__.py", line 3, in <module>
    from . import traitlets
  File "/home/luban/.local/lib/python3.5/site-packages/traitlets/traitlets.py", line 1781
    return repr(f'{value.__module__}.{value.__name__}')
                                                     ^
SyntaxError: invalid syntax
```
I had to manually uninstall the traitlets 5.0.3 version, and install 4.3.3 version to resolve this issue.

### Proposed Solution
Mark version 5.x as incompatible with Python 3.5 in PyPI registry.

**Comment by rmorshea** [comment]
Looks like this was fixed here: https://github.com/ipython/traitlets/blob/master/setup.py#L90

Not too sure what to do about the problem of `pip install traitlets` on Python <3.6 attempting to grab version 5.0.3 though...

Maybe that's something downstream projects will have to sort out now? Thoughts @Carreau @minrk?

I think the only real solution to this would be to delete the release on PyPI, but that's not really something we could safely do.

**Comment by haosong-didi** [comment]
Thanks a lot for the explanation, @rmorshea!

**Comment by minrk** [comment]
> Mark version 5.x as incompatible with Python 3.5 in PyPI registry.

Traitlets 5 is indeed marked as requiring Python 3.7 with the python_requires metadata, as @rmorshea pointed out. You do need to make sure you have a not-too-old version of pip to support this metadata, though. What version of pip do you have?

Try:

    pip install --upgrade setuptools pip

to make sure you have an up-to-date version of pip, and check `pip --version`.

To verify, in a `python:3.5` docker image (`docker run --rm -it python:3.5 bash`):

```bash
pip install notebook
pip freeze
```

installs traitlets-4.3.3

Full env:

<details>

```
$ pip freeze
argon2-cffi==20.1.0
attrs==20.2.0
backcall==0.2.0
bleach==3.1.5
cffi==1.14.2
decorator==4.4.2
defusedxml==0.6.0
entrypoints==0.3
importlib-metadata==1.7.0
ipykernel==5.3.4
ipython==7.9.0
ipython-genutils==0.2.0
jedi==0.17.2
Jinja2==2.11.2
jsonschema==3.2.0
jupyter-client==6.1.7
jupyter-core==4.6.3
MarkupSafe==1.1.1
mistune==0.8.4
nbconvert==5.6.1
nbformat==5.0.7
notebook==6.1.3
packaging==20.4
pandocfilters==1.4.2
parso==0.7.1
pexpect==4.8.0
pickleshare==0.7.5
prometheus-client==0.8.0
prompt-toolkit==2.0.10
ptyprocess==0.6.0
pycparser==2.20
Pygments==2.6.1
pyparsing==2.4.7
pyrsistent==0.16.0
python-dateutil==2.8.1
pyzmq==19.0.2
Send2Trash==1.5.0
six==1.15.0
terminado==0.8.3
testpath==0.4.4
tornado==6.0.4
traitlets==4.3.3
wcwidth==0.2.5
webencodings==0.5.1
zipp==1.2.0
```

</details>

> Maybe that's something downstream projects will have to sort out now?

There shouldn't be anything for anyone to do other than for folks installing with pip to keep their pip up-to-date.

**Comment by rmorshea** [comment]
Thanks @minrk, should have looked back though the history to check what commit the python>=3.7 was added.

That must have been a really old version of `pip` to not know about `python_requires`.

**Comment by rmorshea** [comment]
I think we can close this.
