### ISSUE TITLE
Determine OS testing matrix

### ISSUE THREAD

**Issue by willingc** [ipython/traitlets#654]
https://github.com/ipython/traitlets/pull/653#discussion_r611137655

fyi @rmorshea @takluyver

**Comment by rmorshea** [comment]
There's some stuff to do with file paths for config file loading that might make this worth it.

**Comment by willingc** [comment]
We can also drop Appveyor though if we do the matrix. @rmorshea Do you want to take this?

**Comment by rmorshea** [comment]
Sure. I'll get to it later today.

**Comment by willingc** [comment]
@rmorshea I also send you an invite to be a member of the IPython org.
