### ISSUE TITLE
Update default branch to main

### ISSUE THREAD

**Issue by willingc** [ipython/traitlets#655]

**Comment by rmorshea** [comment]
@minrk @Carreau do you have any idea what the fallout of a change like this might be? I also don't have the ability to make this change so someone else will have to do it.

**Comment by ivanov** [comment]
Done! Here's what github had to say on the matter:

> The default branch has been renamed!
> 
> `master` is now named `main`
> 
> If you have a local clone, you can update it by running:
```
git branch -m master main
git fetch origin
git branch -u origin/main main
git remote set-head origin -a
```

**Comment by ivanov** [comment]
thanks @willingc!

**Comment by Carreau** [comment]
> @minrk @Carreau do you have any idea what the fallout will be? I also don't have the ability to make this change so someone else will have to do it.

Thanks! the only problems I've encountered elsewhere are 
 - My muscle memory ro rebase
 - MrMeeseeks but he is fixed and now looks at the default branch instead of hardcoded "master". 
 - Sometime CI / readthedoc that have "master" hardcoded.
But in general, nothing critical that can't be fixed later.

**Comment by minrk** [comment]
Yeah, I've updated a few repos and never had an issue. There might be a CI reference or two to branch names, but they are easy to fix if they come up. 👍 to doing this across the board at this point.

Some binder links (other CI status badgets as well, perhaps) may have the branch name in them, too. Binder links can be updated to use `HEAD`, which is the default now.

> My muscle memory to rebase

Fortunately for me, my muscle memory is for my own aliases, which I've recently [updated to refer to default branches](https://github.com/minrk/git-stuff/commit/9a680ceee60ebdc78efb801b7632e85789849306). This has helped me a lot switching between repos with different default branch names.
