### ISSUE TITLE
Single list element interpreted as string => error

### ISSUE THREAD

**Issue by fcollonval** [ipython/traitlets#668]
Reported on JupyterLab Gitter by @mlucool

> Hello. What's the correct way to pass --LabApp.extra_labextensions_path=/path/to/dir on the CLI when there is exactly one extra path? Passing that gives "The 'app_dir' trait of a LabApp instance expected a unicode string, not the NoneType None.", but if I do --LabApp.extra_labextensions_path=/path/to/dir --LabApp.extra_labextensions_path=/dev/null it works as expected. More generally, how do you pass a traitlet list of a single value via CLI?

I opened #667 with a unit test that fails.

**Comment by goanpeca** [comment]
Pinging @carreau

**Comment by Carreau** [comment]
From what I can tell the option seem to be `--LabConfig.extra_labextensions_path`, at least it is defined on  `LabConfig` class. I can't reproduce this exact issue, but will look into it.

**Comment by fcollonval** [comment]
@Carreau I opened #667 with a simple unit test that hit the same bug.
