### ISSUE TITLE
Traitlets in strict mode - fail on warnings and/or fail on missing config?

### ISSUE THREAD

**Issue by consideRatio** [ipython/traitlets#677]
Would it be reasonable to implement a strict mode, where warnings become raised errors? It could be useful in a CI system, for example for https://github.com/jupyterhub/zero-to-jupyterhub-k8s/issues/2406.

Concretely, I concluded that I'd like to make this warning become a raised error via configuration of `traitlets` itself somehow.

```
[W 2021-09-26 00:36:57.830 JupyterHub configurable:193] Config option `load_role` not recognized by `JupyterHub`.  Did you mean one of: `load_groups, load_roles`?
```

### Related code

https://github.com/ipython/traitlets/blob/d3777fff41a559efc856198de472cb77ad6d1efd/traitlets/config/configurable.py#L186-L193

**Comment by rmorshea** [comment]
I think you can achieve this with Python's builtin warning [filtering mechanism](https://docs.python.org/3/library/warnings.html#the-warnings-filter) by specifying that matching warnings raise.

**Comment by rmorshea** [comment]
Going to close this for now. Feel free to re-open if you have a different use case.
