### ISSUE TITLE
log: allow log handlers to be configured

### ISSUE THREAD

**Issue by oliver-sanders** [ipython/traitlets#688]
We can configure the log level and the log format, however, I don't think we can configure the log handlers?

There are cases where it would be helpful to be able to configure the application log to write to a file for reference as well as outputting to the default stream handler.

A simple solution would be to add a new trait for defining additional log handlers. A more complex solution could use a [logging config](https://docs.python.org/3/library/logging.config.html?highlight=logging) to configure one or more handlers, potentially with different formats, etc. I don't think users would expect this to be reactive to config changes.

Has this been discussed before? Does this sound sensible?

**Comment by rmorshea** [comment]
I'm not super familiar with configurables in traitlets, but could we just make the [LoggingConfigurable.log](https://github.com/ipython/traitlets/blob/main/traitlets/config/configurable.py#L442) trait configurable instead? That would basically give you [full control](https://docs.python.org/3/howto/logging.html#configuring-logging) over log configuration without changing much.

**Comment by oliver-sanders** [comment]
I don't really want control over the log object, I want to define additional log handlers that traitlets can create/destroy for me with the same lifecycle as the default stream handler it provides.

My use case is writing the log output of Jupyter Servers to configured locations.

**Comment by rmorshea** [comment]
By having control over the application's logger, you would therefore be able to [configure handlers](https://docs.python.org/3/howto/logging.html#configuring-logging) for that logger (or anything else about it for that matter).

If you'd like to be able to configure handlers directly, I'd be happy to take a contribution to that effect (probably a `LoggingConfigurable.log_handlers` list as you suggested), but that'd be a little more involved than just making the `log` trait configurable.

**Comment by oliver-sanders** [comment]
Interested in making a contribution, scoping out opinions before I attempt it.

**Comment by rmorshea** [comment]
The main complication here is that you need to add the handlers to the logger after the logger trait has been assigned. The way to do that would be through a an `@observe` method.

**Comment by oliver-sanders** [comment]
(taking a look at implementing)
