### ISSUE TITLE
Document Application class overview

### ISSUE THREAD

**Issue by metaperl** [ipython/traitlets#708]
The [overview Docs for the `Application` class](https://traitlets.readthedocs.io/en/stable/config.html#the-main-concepts) has a number of statements that I find do not lead to complete understanding:

> An application is a process that does a specific job. 

I like this sentence. I was having problems with chaining two
applications together by invoking the 2nd application from the 1st
(singleton violation). Now, after reading this sentence, I understand
that I should call the 2nd application by calling another
process. This will avoid the Singleton Application constraint that I
was suffering from.

> Each application reads one or more configuration files 

From where? How? Having done some digging, I'm guessing that
[load_config_file](https://traitlets.readthedocs.io/en/stable/config-api.html#traitlets.config.Application.load_config_file) is explicitly called to do the loading. But there are no examples of
this and it is not explicitly stated.

> This configuration object is then passed to the configurable objects
> that the application creates. 

How is the configuration object passed? Is there some sample,
**simple** code completely exemplifying what this sentence states?

> These configurable objects implement the actual logic of the
> application and know how to configure themselves given the
> configuration object. 

OK, but how are the configurable objects given the configuration
object? Again, a complete, small example of an `Application` configuring 1 or
2 `Configurable` instances would be ideal. 

The configuration would be via config files but of course could be
overriden by the command-line.

**Comment by metaperl** [comment]
>  But there are no examples of this and it is not explicitly stated.

There is an example but the docs dont link to it - https://github.com/ipython/traitlets/blob/main/examples/myapp.py

**Comment by azjps** [comment]
Docs have been updated a bit, feel free to submit a PR to improve docs if you encounter anything missing.
