### ISSUE TITLE
Document flag configuration

### ISSUE THREAD

**Issue by metaperl** [ipython/traitlets#709]
If one wants to have a boolean attribute of a Configurable/Application set via a flag, there is [quite a bit of configuration to do](https://towardsdatascience.com/tutorial-create-a-python-cli-package-a2410b47af35).

Unfortunately, this configuration is not well-documented or exemplified.

**Comment by metaperl** [comment]
I've done some digging. Paring down this code provides a good example of creating boolean flags - https://github.com/ipython/ipython/blob/master/IPython/terminal/ipapp.py

# key points:

## the boolean_flag helper

    from traitlets.config.application import boolean_flag

## Creating flags

Further down in same IPython class

```python

frontend_flags = {}
addflag = lambda *args: frontend_flags.update(boolean_flag(*args))
addflag('autoedit-syntax', 'TerminalInteractiveShell.autoedit_syntax',
        'Turn on auto editing of files with syntax errors.',
        'Turn off auto editing of files with syntax errors.'
)
``

**Comment by metaperl** [comment]
More digging. if the docs had linked to [the example source code](https://github.com/ipython/traitlets/blob/main/examples/myapp.py) then a lot of the docs would've been easier to follow.

**Comment by azjps** [comment]
Docs have been updated a bit, feel free to submit a PR to improve docs if you encounter anything missing.
