### ISSUE TITLE
`classes` attribute of Application used in example, not but not documented

### ISSUE THREAD

**Issue by metaperl** [ipython/traitlets#712]
In the [sample application on line 55](https://github.com/ipython/traitlets/blob/main/examples/myapp.py#L55) we see:

    classes = List([Bar, Foo])

but to learn what classes is we must read [this comment in the code](https://github.com/ipython/traitlets/blob/main/traitlets/config/application.py#L161):

```
    # A sequence of Configurable subclasses whose config=True attributes will
    # be exposed at the command line.
```

which basically means that no one will understand the sample code after reading the docs.

**Comment by azjps** [comment]
Docs have been updated a bit, feel free to submit a PR to improve docs if you encounter anything missing.
