### ISSUE TITLE
extra_args not documented

### ISSUE THREAD

**Issue by metaperl** [ipython/traitlets#714]
[`extra_args`](https://github.com/ipython/traitlets/blob/34f596dd03b98434900a7d31c912fc168342bb80/traitlets/config/application.py#L280) apparently has something to do with "extra command-line arguments that don't set config values" but nowhere is this functionality documented. I noticed it in a [towards data science article](https://towardsdatascience.com/tutorial-create-a-python-cli-package-a2410b47af35). 

tutorial and reference documentation would be ideal.

[another issue](https://github.com/ipython/traitlets/issues/658) does reference `extra_args` also.

**Comment by metaperl** [comment]
Also, what motivated `extra_args`? Why would you want extra command-line arguments that don't set config values?

**Comment by azjps** [comment]
Docs have been updated a bit, feel free to submit a PR to improve docs if you encounter anything missing.
