### ISSUE TITLE
compatibility of Traitlets-5.2.1post0 with QtConsole-5.3.0 ?

### ISSUE THREAD

**Issue by stonebig** [ipython/traitlets#734]
hi I have this error with Qtconssole-5.3.0  and Traitlets-5.2.1post0 on Windows 

![image](https://user-images.githubusercontent.com/4312421/170837126-ebd819bb-18a5-4b4f-88b9-0ebf91c8fd0f.png)

**Comment by stonebig** [comment]
backpedaling to traitlets-5.1.1 resolve the current issue

**Comment by JanB1** [comment]
Related toPR: #724
