### ISSUE TITLE
How to get the value of a trait that is the value of a key returned from .traits()

### ISSUE THREAD

**Issue by metaperl** [ipython/traitlets#746]
I am putting this here to that others can see how to access the values within the dict returned by `.traits()`. As you can see, the way to get the value is via `._trait_values[]`:

```
from traitlets.config import Application
from traitlets import List, Dict, Integer, Unicode, validate, TraitError


class App(Application):

    aliases = {"x": "App.x", "y": "App.y"}
    x = Unicode().tag(config=True)
    y = Integer(allow_none=True).tag(config=True)

    def start(self):
        self.x = "yohoho"
        self.y = 99
        print(f"as dict = {self.traits()}")

        d = self.traits()
        print(self._trait_values['x']) ### success


if __name__ == "__main__":
    App.launch_instance()
```

**Comment by azjps** [comment]
`getattr(self, "x")` works too

**Comment by rmorshea** [comment]
Using `_trait_values` is not recommended - it is a private attribute and as such could be changed without a normal deprecation warning. You should access trait values via normal attribute access:

```python
obj.my_trait
getattr(obj, "my_trait")
```

If for some reason you need to access all trait values in bulk, there is a `trait_values()` method that will return a dictionary of trait values. You can even filter them based on any tags you've applied to your traits:

```python
all_trait_values = obj.trait_values()
configurable_trait_values = obj.trait_values(config=True)
```
