### ISSUE TITLE
Missing project description at PyPI

### ISSUE THREAD

**Issue by mtelka** [ipython/traitlets#800]
Starting with version 5.2.1 the `traitlets` project is missing the project description at PyPI.  There is `Traitlets Python configuration system` up to version 5.2.0 and since 5.2.1 PyPI shows just `No project description provided`.  I suspect the switch to hatchling caused that.  Could you please add the description back?  Thank you.

**Comment by blink1073** [comment]
Thanks for the heads up: https://github.com/ipython/traitlets/pull/801
