### ISSUE TITLE
`DeprecationWarning:` in traitlets

### ISSUE THREAD

**Issue by yuvalshi0** [ipython/traitlets#819]
Hi, I've encountered this warning when I run my tests

`.venv/lib/python3.10/site-packages/traitlets/traitlets.py:1016: 101 warnings
****/.venv/lib***/python3.10/site-packages/traitlets/traitlets.py:1016: DeprecationWarning: Widget._active_widgets is deprecated.
    value = getattr(cls, name)
`

**Comment by rmorshea** [comment]
What versions of traitlets and ipywidgets are you using?

**Comment by yuvalshi0** [comment]
> What versions of traitlets and ipywidgets are you using?
```
traitlets                               5.8.0
ipywidgets                          8.0.3
```

**Comment by rmorshea** [comment]
Just to help out the investigation. The message is being reported [here](https://github.com/ipython/traitlets/blob/278e5242484536f04d47ce5bf2dcc67348ac533e/traitlets/traitlets.py#L1016), but the warning originates [here](https://github.com/jupyter-widgets/ipywidgets/blob/eacd961c2e029fd9db036c0f6440579565983c91/python/ipywidgets/ipywidgets/widgets/widget.py#L307-L345) in ipywidgets.

**Comment by rmorshea** [comment]
Somehow [this check](https://github.com/jupyter-widgets/ipywidgets/blob/eacd961c2e029fd9db036c0f6440579565983c91/python/ipywidgets/ipywidgets/widgets/widget.py#L313) is not working as expected. I can't tell exactly what's going wrong just from reading the code though. It seem like it ought to work.

**Comment by yuvalshi0** [comment]
> Somehow [this check](https://github.com/jupyter-widgets/ipywidgets/blob/eacd961c2e029fd9db036c0f6440579565983c91/python/ipywidgets/ipywidgets/widgets/widget.py#L313) is not working as expected. I can't tell exactly what's going wrong just from reading the code though. It seem like it ought to work.

I just upgraded my widgets to 8.0.4 and it removed the warning, the check you sent was changed between tag 8.0.3 and 8.0.4 to add the `setup_class` `co_name`, thanks for the tip!
