### ISSUE TITLE
Bug in version 5.8.0

### ISSUE THREAD

**Issue by gt-fm-4562** [ipython/traitlets#823]
https://github.com/ipython/traitlets/blob/2cdbe59606ea23ee835f651303f8f75e0aeb9efd/traitlets/traitlets.py#L1022-L1030

Getting error UnboundLocalError: local variable 'mro_trait' referenced before assignment.

**Comment by blink1073** [comment]
Hi @gt-fm-4562, can you provide some code that triggers this condition?

cc @maartenbreddels

**Comment by maartenbreddels** [comment]
Thanks for the report @gt-fm-4562 , and thanks for the ping @blink1073 

@gt-fm-4562 could you confirm that https://github.com/ipython/traitlets/pull/824 fixes your issue?

**Comment by gt-fm-4562** [comment]
It certainly did fix the issue yes. Thanks for the quick fix!
