### ISSUE TITLE
Why does TraitType.get accept cls?

### ISSUE THREAD

**Issue by NeilGirdhar** [ipython/traitlets#86]
I sometimes call `trait.get(obj)` directly, but I have to pass something for the argument `cls`, which is ultimately unused.  What's the long term plan for this argument?

**Comment by rmorshea** [comment]
You're right, it should probably be removed.

**Comment by NeilGirdhar** [comment]
@rmorshea Any progress on this?

**Comment by rmorshea** [comment]
@NeilGirdhar - see #170
