### ISSUE TITLE
`__doc__` no longer contains the traitlets help string for reference type traitlets (Dict, List, ...)

### ISSUE THREAD

**Issue by consideRatio** [ipython/traitlets#869]
https://github.com/jupyterhub/autodoc_traits is a project that help generate documentation for sphinx by inspecting traitlets. Since #818 was merged and released in 5.10.0, it has experienced issues detecting traitlets help strings via a `__doc__` attribute for some traitlet types.

Specifically the help string is no longer found in `__doc__` attribute of the traitlet types Dict, List, Instance, and Command traitlets, but it still is found for the traitlet types Bool, Integer, Unicode. Maybe this is relating to reference/value type differences?

I've opened https://github.com/jupyterhub/autodoc-traits/issues/55 about it, but since I'm unsure if its a bug in this project or `autodoc_traits` at this point, I'm opening this issue as well for now.

**Comment by blink1073** [comment]
I tried the autodoc test suite with `traitlets@5.10.0` and was able to reproduce the failures.  With 5.10.1 all the tests pass:

```
======================================== 16 passed in 6.05s ========================================
```

**Comment by consideRatio** [comment]
Thank you @blink1073 !!!
