### ISSUE TITLE
test_complete_custom_completers failing

### ISSUE THREAD

**Issue by mweinelt** [ipython/traitlets#902]
We are seeing `test_complete_custom_completers` fail with traitlets 5.14.1 and argcomplete 3.2.3 on Python 3.12.3/3.11.9 on Linux.

```python
_______________ TestArgcomplete.test_complete_custom_completers ________________

self = <tests.config.test_argcomplete.TestArgcomplete object at 0x7ffff5c1e950>
argcomplete_on = None

    def test_complete_custom_completers(self, argcomplete_on):
        app = ArgcompleteApp()
        # test pre-defined completers for Bool/Enum
>       assert set(self.run_completer(app, "app --Application.log_level=")) > {"DEBUG", "INFO"}
E       AssertionError: assert {''} > {'INFO', 'DEBUG'}
E         
E         Extra items in the right set:
E         'INFO'
E         'DEBUG'

app        = <tests.config.test_argcomplete.ArgcompleteApp object at 0x7ffff5617a50>
argcomplete_on = None
self       = <tests.config.test_argcomplete.TestArgcomplete object at 0x7ffff5c1e950>

tests/config/test_argcomplete.py:157: AssertionError
```

**Comment by mweinelt** [comment]
Thanks for checking up. I agree this is something on our end.

**Comment by shadchin** [comment]
I have the same problem.

Python 3.12.2 - OK
Python 3.12.3 - Fail

**Comment by azjps** [comment]
> I have the same problem.
> 
> Python 3.12.2 and argcomplete 3.2.3 - OK Python 3.12.3 and argcomplete 3.2.3 - Fail Python 3.12.3 and argcomplete 3.3.0 - OK
> 
> UPD: upgrade argcomplete to 3.3.0, fix it

Thanks you're right, I incidentally tested with the same versions. Presumably the issue was [fixed in this upstream commit in `argcomplete`](https://github.com/kislyuk/argcomplete/commit/54a4846b3a774cd9037167898f3cce38ba9d58e8).
