### ISSUE TITLE
The "install_requires" keyword doesn't work with distutils

### ISSUE THREAD

**Issue by SnarkBoojum** [ipython/traitlets#95]
It should be "requires", so I suggest the line:
setup_args['requires'] = setuptools_args['install_requires'] = [
instead of what appears now in setup.py.

**Comment by minrk** [comment]
install_requires is only added to setup args when setuptools is already loaded, so it's never passed to plain distutils.

**Comment by SnarkBoojum** [comment]
Yes, so distutils doesn't get the "requires" it needs, and my debian packaging doesn't pick the dependencies correctly.

**Comment by minrk** [comment]
How is the package constructed?

**Comment by SnarkBoojum** [comment]
The package is built with a debian tool (pybuild), which calls setup.py with the actual arguments -- and then parses some resulting files to get metadata about the package.

If setup.py's install target uses distutils but distutils' setup doesn't get the 'requires', then the dep information will be lost.

I must admit I don't quite follow why setuptools is used at some steps and not at others [I think I'll hit the problem with quite a few IPython/Jupyter packages... let's discuss here...]

**Comment by SnarkBoojum** [comment]
Ok, I added a package-patch to make setuptools used for each and every target -- that way everything works.

**Comment by SylvainCorlay** [comment]
@SnarkBoojum - I don't know much about Debian packaging but I was wondering if this type of "package patch" should be contributed to the traitlets repo or if it is an idiosyncrasy of Debian that should not be here.
